apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gitea
  name: gitea
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    {{- if (default true .Values.skyforge.gitea.ssh.enabled) }}
    - name: ssh
      port: {{ default 22 .Values.skyforge.gitea.ssh.servicePort }}
      targetPort: ssh
    {{- end }}
  selector:
    app.kubernetes.io/name: gitea
