apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: netbox-scripts
  name: netbox-scripts
spec:
  accessModes:
    - ReadWriteOnce
{{ with .Values.skyforge.netbox.storage.storageClassName }}
  storageClassName: {{ . | quote }}
{{ end }}
  resources:
    requests:
      storage: 5Gi
