apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: platform-data
  name: platform-data
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.skyforge.platformData.storage.accessMode | quote }}
{{ with .Values.skyforge.platformData.storage.storageClassName }}
  storageClassName: {{ . | quote }}
{{ end }}
  resources:
    requests:
      storage: {{ default "5Gi" .Values.skyforge.platformData.storage.size | quote }}
