apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: redis-data
  name: redis-data
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.skyforge.redis.storage.accessMode | quote }}
{{ with .Values.skyforge.redis.storage.storageClassName }}
  storageClassName: {{ . | quote }}
{{ end }}
  resources:
    requests:
      storage: {{ default "5Gi" .Values.skyforge.redis.storage.size | quote }}
