apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: s3gw-data
  name: s3gw-data
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.skyforge.s3gw.persistence.accessMode | quote }}
{{ with .Values.skyforge.s3gw.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
{{ end }}
  resources:
    requests:
      storage: {{ .Values.skyforge.s3gw.persistence.size | quote }}
