apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: yaade-data
  name: yaade-data
spec:
  accessModes:
    - ReadWriteOnce
{{ with .Values.skyforge.yaade.storage.storageClassName }}
  storageClassName: {{ . | quote }}
{{ end }}
  resources:
    requests:
      storage: 5Gi
