apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api-docs
  name: api-docs
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api-docs
