apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres-s3
  labels:
    io.kompose.service: backup-postgres-s3
spec:
  schedule: "17 3 * * *" # daily 03:17 UTC
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: postgres:15-alpine
              command: ["/bin/sh","-lc"]
              args:
                - |
                  set -eu
                  apk add --no-cache aws-cli >/dev/null
                  ts="$(date -u +%Y%m%dT%H%M%SZ)"
                  out="/tmp/skyforge-postgres-${ts}.sql.gz"

                  : "${BACKUP_S3_BUCKET:?set BACKUP_S3_BUCKET}"
                  prefix="${BACKUP_S3_PREFIX:-skyforge-backups/postgres}"

                  export PGPASSWORD="$(cat /run/secrets/postgres-skyforge-password)"
                  echo "Dumping Postgres..."
                  pg_dumpall -h db -U skyforge | gzip -9 > "${out}"

                  echo "Uploading to s3://${BACKUP_S3_BUCKET}/${prefix}/"
                  aws s3 cp "${out}" "s3://${BACKUP_S3_BUCKET}/${prefix}/$(basename "${out}")"
                  echo "Done."
              env:
                - name: AWS_PROFILE
                  value: default
                - name: AWS_SDK_LOAD_CONFIG
                  value: "1"
                - name: AWS_SHARED_CREDENTIALS_FILE
                  value: /run/secrets/aws-terraform-shared-credentials
                - name: BACKUP_S3_BUCKET
                  value: ""
                - name: BACKUP_S3_PREFIX
                  value: "skyforge-backups/postgres"
              volumeMounts:
                - name: run-secrets
                  mountPath: /run/secrets
                  readOnly: true
          volumes:
            - name: run-secrets
              projected:
                sources:
                  - secret:
                      name: postgres-skyforge-password
                      items:
                        - key: postgres-skyforge-password
                          path: postgres-skyforge-password
                  - secret:
                      name: aws-terraform-shared-credentials
                      items:
                        - key: aws-terraform-shared-credentials
                          path: aws-terraform-shared-credentials
