apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: coder
  name: coder
spec:
  ports:
    - name: "7080"
      port: 7080
      targetPort: 7080
  selector:
    io.kompose.service: coder
