apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: coder-data
  name: coder-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
