apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: code-server-home
  name: code-server-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
