apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  ports:
    - name: http
      port: 5556
      targetPort: 5556
  selector:
    io.kompose.service: dex
