apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hoppscotch
  name: hoppscotch
spec:
  ports:
    - name: web
      port: 80
      targetPort: 3000
    - name: admin
      port: 3100
      targetPort: 3100
    - name: backend
      port: 3170
      targetPort: 3170
  selector:
    io.kompose.service: hoppscotch
