apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hoppscotch
  name: hoppscotch
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: hoppscotch
