apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: minio-ldap-init
  name: minio-ldap-init
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        io.kompose.service: minio-ldap-init
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - args:
            - |
              set -euo pipefail
              MINIO_ROOT_USER="$(cat /run/secrets/object-storage-root-user | tr -d '\r\n')"
              MINIO_ROOT_PASSWORD="$(cat /run/secrets/object-storage-root-password | tr -d '\r\n')"
              ldap_url="$(cat /run/secrets/skyforge-ldap-url | tr -d '\r\n')"
              needtls="$(cat /run/secrets/skyforge-ldap-needtls | tr -d '\r\n')"
              search_base_dn="$(cat /run/secrets/skyforge-ldap-searchdn | tr -d '\r\n')"
              user_filter="$(cat /run/secrets/skyforge-ldap-searchfilter | tr -d '\r\n')"
              bind_dn="$(cat /run/secrets/skyforge-ldap-binddn | tr -d '\r\n')"
              bind_password="$(cat /run/secrets/skyforge-ldap-bindpassword | tr -d '\r\n')"
              base_dn="${SKYFORGE_LDAP_BASEDN:-}"

              if [ -z "${ldap_url}" ]; then
                echo "SKYFORGE_LDAP_URL is empty; skipping object storage LDAP config."
                exit 0
              fi
              if [ -z "${bind_dn}" ]; then
                echo "LDAP lookup bind DN is empty; skipping object storage LDAP config."
                exit 0
              fi

              scheme="ldap"
              hostport="${ldap_url}"
              case "${ldap_url}" in
                ldaps://*) scheme="ldaps"; hostport="${ldap_url#ldaps://}" ;;
                ldap://*)  scheme="ldap";  hostport="${ldap_url#ldap://}" ;;
              esac

              tls_skip_verify="off"
              if [ "${SKYFORGE_LDAP_SKIP_TLS_VERIFY:-false}" = "true" ]; then
                tls_skip_verify="on"
              fi

              server_insecure="off"
              server_starttls="off"
              if [ "${scheme}" = "ldap" ]; then
                if [ "${needtls}" = "true" ]; then
                  server_starttls="on"
                else
                  server_insecure="on"
                fi
              fi

              echo "Waiting for object storage..."
              for i in $(seq 1 60); do
                if mc alias set local http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" >/dev/null 2>&1; then
                  break
                fi
                sleep 1
              done
              mc alias set local http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" >/dev/null

              group_base_dn=""
              group_filter=""
              if [ -n "${base_dn}" ]; then
                group_base_dn="ou=Groups,${base_dn}"
                group_filter="(&(objectClass=posixGroup)(memberUid=%s))"
              fi

              if [ -n "${group_base_dn}" ] && [ -n "${group_filter}" ]; then
                if ! mc idp ldap add local/ \
                  "server_addr=${hostport}" \
                  "server_insecure=${server_insecure}" \
                  "server_starttls=${server_starttls}" \
                  "tls_skip_verify=${tls_skip_verify}" \
                  "lookup_bind_dn=${bind_dn}" \
                  "lookup_bind_password=${bind_password}" \
                  "user_dn_search_base_dn=${search_base_dn}" \
                  "user_dn_search_filter=${user_filter}" \
                  "user_dn_attributes=uid" \
                  "group_search_base_dn=${group_base_dn}" \
                  "group_search_filter=${group_filter}" >/dev/null 2>&1; then
                  mc idp ldap update local/ \
                    "server_addr=${hostport}" \
                    "server_insecure=${server_insecure}" \
                    "server_starttls=${server_starttls}" \
                    "tls_skip_verify=${tls_skip_verify}" \
                    "lookup_bind_dn=${bind_dn}" \
                    "lookup_bind_password=${bind_password}" \
                    "user_dn_search_base_dn=${search_base_dn}" \
                    "user_dn_search_filter=${user_filter}" \
                    "user_dn_attributes=uid" \
                    "group_search_base_dn=${group_base_dn}" \
                    "group_search_filter=${group_filter}" >/dev/null
                fi
              else
                if ! mc idp ldap add local/ \
                  "server_addr=${hostport}" \
                  "server_insecure=${server_insecure}" \
                  "server_starttls=${server_starttls}" \
                  "tls_skip_verify=${tls_skip_verify}" \
                  "lookup_bind_dn=${bind_dn}" \
                  "lookup_bind_password=${bind_password}" \
                  "user_dn_search_base_dn=${search_base_dn}" \
                  "user_dn_search_filter=${user_filter}" \
                  "user_dn_attributes=uid" >/dev/null 2>&1; then
                  mc idp ldap update local/ \
                    "server_addr=${hostport}" \
                    "server_insecure=${server_insecure}" \
                    "server_starttls=${server_starttls}" \
                    "tls_skip_verify=${tls_skip_verify}" \
                    "lookup_bind_dn=${bind_dn}" \
                    "lookup_bind_password=${bind_password}" \
                    "user_dn_search_base_dn=${search_base_dn}" \
                    "user_dn_search_filter=${user_filter}" \
                    "user_dn_attributes=uid" >/dev/null
                fi
              fi
              mc idp ldap enable local/ >/dev/null || true

              console_group="${SKYFORGE_MINIO_LDAP_CONSOLE_GROUP:-}"
              if [ -n "${console_group}" ]; then
                # Grant LDAP users access to the console + buckets via group membership.
                # NOTE: This must be configured via the LDAP IDP policy bindings (not IAM groups).
                group_dn="cn=${console_group},ou=Groups,${base_dn}"
                mc idp ldap policy attach local/ consoleAdmin readwrite --group "${group_dn}" >/dev/null 2>&1 || true
              fi

              MC_DISABLE_PAGER=true MC_QUIET=1 mc admin service restart --json local >/dev/null
              echo "Object storage LDAP configured."
          command:
            - /bin/sh
            - -lc
          env:
            - name: SKYFORGE_MINIO_LDAP_CONSOLE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_MINIO_LDAP_CONSOLE_GROUP
            - name: SKYFORGE_LDAP_BASEDN
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_LDAP_BASEDN
            - name: SKYFORGE_LDAP_SKIP_TLS_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_LDAP_SKIP_TLS_VERIFY
          image: minio/mc:RELEASE.2024-11-17T19-35-25Z
          name: minio-ldap-init
          volumeMounts:
            - mountPath: /run/secrets
              name: run-secrets
              readOnly: true
      volumes:
        - name: run-secrets
          projected:
            sources:
              - secret:
                  items:
                    - key: object-storage-root-user
                      path: object-storage-root-user
                  name: object-storage-root-user
              - secret:
                  items:
                    - key: object-storage-root-password
                      path: object-storage-root-password
                  name: object-storage-root-password
              - secret:
                  items:
                    - key: skyforge-ldap-url
                      path: skyforge-ldap-url
                  name: skyforge-ldap-url
              - secret:
                  items:
                    - key: skyforge-ldap-searchdn
                      path: skyforge-ldap-searchdn
                  name: skyforge-ldap-searchdn
              - secret:
                  items:
                    - key: skyforge-ldap-searchfilter
                      path: skyforge-ldap-searchfilter
                  name: skyforge-ldap-searchfilter
              - secret:
                  items:
                    - key: skyforge-ldap-binddn
                      path: skyforge-ldap-binddn
                  name: skyforge-ldap-binddn
              - secret:
                  items:
                    - key: skyforge-ldap-bindpassword
                      path: skyforge-ldap-bindpassword
                  name: skyforge-ldap-bindpassword
              - secret:
                  items:
                    - key: skyforge-ldap-needtls
                      path: skyforge-ldap-needtls
                  name: skyforge-ldap-needtls
