apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: minio-init
  name: minio-init
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        io.kompose.service: minio-init
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - |
              set -euo pipefail
              export MINIO_ROOT_USER="$(cat /run/secrets/object-storage-root-user)"
              export MINIO_ROOT_PASSWORD="$(cat /run/secrets/object-storage-root-password)"
              echo "Waiting for object storage..."
              for i in $(seq 1 60); do
                if mc alias set local http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" >/dev/null 2>&1; then
                  break
                fi
                sleep 1
              done
              mc alias set local http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}" >/dev/null
              mc mb -p "local/${SKYFORGE_FILES_BUCKET}" || true
              cat > /tmp/anonymous-put-get.json <<EOF
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": { "AWS": ["*"] },
                    "Action": [
                      "s3:ListBucket",
                      "s3:GetBucketLocation",
                      "s3:ListBucketMultipartUploads"
                    ],
                    "Resource": ["arn:aws:s3:::${SKYFORGE_FILES_BUCKET}"]
                  },
                  {
                    "Effect": "Allow",
                    "Principal": { "AWS": ["*"] },
                    "Action": [
                      "s3:GetObject",
                      "s3:PutObject",
                      "s3:DeleteObject",
                      "s3:AbortMultipartUpload",
                      "s3:ListMultipartUploadParts"
                    ],
                    "Resource": ["arn:aws:s3:::${SKYFORGE_FILES_BUCKET}/*"]
                  }
                ]
              }
              EOF
              mc anonymous set-json /tmp/anonymous-put-get.json "local/${SKYFORGE_FILES_BUCKET}"
              echo "Object storage bucket ready: ${SKYFORGE_FILES_BUCKET} (anonymous PUT/GET enabled)"
          command:
            - /bin/sh
            - -lc
          env:
            - name: SKYFORGE_FILES_BUCKET
              value: skyforge-files
          image: quay.io/minio/mc:RELEASE.2024-11-17T19-35-25Z
          name: minio-init
          volumeMounts:
            - mountPath: /run/secrets
              name: run-secrets
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: run-secrets
          projected:
            sources:
              - secret:
                  items:
                    - key: object-storage-root-user
                      path: object-storage-root-user
                  name: object-storage-root-user
              - secret:
                  items:
                    - key: object-storage-root-password
                      path: object-storage-root-password
                  name: object-storage-root-password
