apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nautobot-reports
  name: nautobot-reports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
