apiVersion: v1
kind: Pod
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "11"
  labels:
    io.kompose.service: nautobot-init
  name: nautobot-init
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - set -euo pipefail; for dir in media reports jobs; do echo "Initializing /$dir"; mkdir -p "/$dir"; chown -R 999:999 "/$dir"; done; echo 'Nautobot volumes ready'
      command:
        - /bin/sh
        - -c
      image: alpine:3.20
      name: nautobot-init
      volumeMounts:
        - mountPath: /media
          name: nautobot-media
        - mountPath: /reports
          name: nautobot-reports
        - mountPath: /jobs
          name: nautobot-jobs
  restartPolicy: Never
  volumes:
    - name: nautobot-media
      persistentVolumeClaim:
        claimName: nautobot-media
    - name: nautobot-reports
      persistentVolumeClaim:
        claimName: nautobot-reports
    - name: nautobot-jobs
      persistentVolumeClaim:
        claimName: nautobot-jobs
