apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: netbox-media
  name: netbox-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
