apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: netbox-reports
  name: netbox-reports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
