apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: platform-data
  name: platform-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
