apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: skyforge-server-data
  name: skyforge-server-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
