apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    io.kompose.service: skyforge-migrate
  name: skyforge-migrate
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        io.kompose.service: skyforge-migrate
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: skyforge-migrate
          image: arigaio/atlas:latest-alpine
          imagePullPolicy: Always
          workingDir: /app
          command:
            - /bin/sh
            - -c
          args:
            - >-
              set -euo pipefail;
              db_url="postgres://${SKYFORGE_DB_USER}:${SKYFORGE_DB_PASSWORD}@${SKYFORGE_DB_HOST}:${SKYFORGE_DB_PORT}/${SKYFORGE_DB_NAME}?sslmode=${SKYFORGE_DB_SSLMODE}";
              echo "Running Skyforge migrations...";
              for i in $(seq 1 60); do
                if atlas migrate apply --config file:///app/atlas.hcl --env prod --var db_url="${db_url}"; then
                  echo "Skyforge migrations complete.";
                  exit 0;
                fi
                echo "Migrations not ready yet; retrying (${i}/60)...";
                sleep 2;
              done;
              echo "Skyforge migrations failed after retries." >&2;
              exit 1;
          env:
            - name: SKYFORGE_DB_HOST
              value: db
            - name: SKYFORGE_DB_PORT
              value: "5432"
            - name: SKYFORGE_DB_NAME
              value: skyforge_server
            - name: SKYFORGE_DB_USER
              value: skyforge_server
            - name: SKYFORGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-skyforge-server-password
                  key: db-skyforge-server-password
            - name: SKYFORGE_DB_SSLMODE
              value: disable
            - name: ATLAS_CONFIG
              value: /app/atlas.hcl
          volumeMounts:
            - mountPath: /app
              name: skyforge-migrate-config
              readOnly: true
      volumes:
        - name: skyforge-migrate-config
          configMap:
            name: skyforge-migrate-config
            items:
              - key: atlas.hcl
                path: atlas.hcl
              - key: atlas.sum
                path: skyforge/migrations/atlas.sum
              - key: 20251220000100_init.up.sql
                path: skyforge/migrations/20251220000100_init.up.sql
              - key: 20251221000100_cloud_credentials.up.sql
                path: skyforge/migrations/20251221000100_cloud_credentials.up.sql
              - key: 20251222000100_project_visibility.up.sql
                path: skyforge/migrations/20251222000100_project_visibility.up.sql
              - key: 20251223000100_governance_tables.up.sql
                path: skyforge/migrations/20251223000100_governance_tables.up.sql
              - key: 20251223000200_deployments.up.sql
                path: skyforge/migrations/20251223000200_deployments.up.sql
              - key: 20251224000100_labpp_templates.up.sql
                path: skyforge/migrations/20251224000100_labpp_templates.up.sql
              - key: 20251227000100_deployments_labpp.up.sql
                path: skyforge/migrations/20251227000100_deployments_labpp.up.sql
              - key: 20251229000100_dns_tokens.up.sql
                path: skyforge/migrations/20251229000100_dns_tokens.up.sql
              - key: 20251230000100_syslog_events.up.sql
                path: skyforge/migrations/20251230000100_syslog_events.up.sql
              - key: 20251230000200_webhooks_snmp.up.sql
                path: skyforge/migrations/20251230000200_webhooks_snmp.up.sql
              - key: 20251231000100_containerlab_templates.up.sql
                path: skyforge/migrations/20251231000100_containerlab_templates.up.sql
              - key: 20260101000100_pki_certs.up.sql
                path: skyforge/migrations/20260101000100_pki_certs.up.sql
              - key: 20260102000100_tasks.up.sql
                path: skyforge/migrations/20260102000100_tasks.up.sql
              - key: 20260102000200_variable_groups.up.sql
                path: skyforge/migrations/20260102000200_variable_groups.up.sql
              - key: 20260102000400_forward_credentials.up.sql
                path: skyforge/migrations/20260102000400_forward_credentials.up.sql
              - key: 20260102000500_forward_collectors.up.sql
                path: skyforge/migrations/20260102000500_forward_collectors.up.sql
              - key: 20260102000600_pki_ssh_certs.up.sql
                path: skyforge/migrations/20260102000600_pki_ssh_certs.up.sql
              - key: 20260103000100_workspace_rename.up.sql
                path: skyforge/migrations/20260103000100_workspace_rename.up.sql
              - key: 20260110120000_rename_tofu_to_terraform.up.sql
                path: skyforge/migrations/20260110120000_rename_tofu_to_terraform.up.sql
              - key: 20260112000100_task_events.up.sql
                path: skyforge/migrations/20260112000100_task_events.up.sql
              - key: 20260113000300_forward_device_types.up.sql
                path: skyforge/migrations/20260113000300_forward_device_types.up.sql
              - key: 20260114000100_node_metrics_and_heartbeats.up.sql
                path: skyforge/migrations/20260114000100_node_metrics_and_heartbeats.up.sql
              - key: 20260114000200_ldap_password_cache.up.sql
                path: skyforge/migrations/20260114000200_ldap_password_cache.up.sql
              - key: 20260114000300_workspace_servers.up.sql
                path: skyforge/migrations/20260114000300_workspace_servers.up.sql
              - key: 20260115000100_drop_legacy_workspace_id.up.sql
                path: skyforge/migrations/20260115000100_drop_legacy_workspace_id.up.sql
              - key: 20260115000200_workspace_template_sources.up.sql
                path: skyforge/migrations/20260115000200_workspace_template_sources.up.sql
              - key: 20260116000100_task_priority.up.sql
                path: skyforge/migrations/20260116000100_task_priority.up.sql
