apiVersion: v1
kind: ServiceAccount
metadata:
  name: skyforge-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skyforge-server-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
  resourceNames: ["yaade"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skyforge-server-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skyforge-server-scaler
subjects:
  - kind: ServiceAccount
    name: skyforge-server
