apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: webhooks-data
  name: webhooks-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

