apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: yaade-data
  name: yaade-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
