apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: yaade-oidc-init
  name: yaade-oidc-init
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - |
          set -euo pipefail

          base_path="${YAADE_BASE_PATH:-/api-testing}"
          base_url="http://yaade${base_path}"
          login_url="${base_url}/api/login"
          config_url="${base_url}/api/config/auth_config"
          callback_url="https://${SKYFORGE_HOSTNAME}${base_path}/callback-dex"

          echo "Waiting for Yaade API..."
          for i in $(seq 1 60); do
            if curl -sf "${base_url}/api/loginProviders" >/dev/null 2>&1; then
              break
            fi
            sleep 2
          done

          admin_password="$(cat /run/secrets/yaade-admin-password | tr -d '\n')"
          oidc_discovery="$(cat /run/secrets/skyforge-oidc-discovery-url | tr -d '\n')"
          client_id="$(cat /run/secrets/yaade-oidc-client-id | tr -d '\n')"
          client_secret="$(cat /run/secrets/dex-client-yaade-secret | tr -d '\n')"
          oidc_site="https://${SKYFORGE_HOSTNAME}/dex"

          if [ -z "${admin_password}" ] || [ -z "${oidc_discovery}" ] || [ -z "${client_id}" ] || [ -z "${client_secret}" ]; then
            echo "Missing OIDC settings; skipping Yaade OIDC init."
            exit 0
          fi

          echo "Logging into Yaade as ${YAADE_ADMIN_USERNAME}..."
          curl -sf -c /tmp/yaade-cookie \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"${YAADE_ADMIN_USERNAME}\",\"password\":\"${admin_password}\"}" \
            "${login_url}" >/dev/null

          cat >/tmp/yaade-auth.json <<EOF
          {"providers":[{"id":"dex","label":"Skyforge SSO","provider":"oidc-discovery","params":{"site":"${oidc_site}","clientId":"${client_id}","clientSecret":"${client_secret}","callbackUrl":"${callback_url}","scopes":["openid","email","profile","groups"],"fields":{"username":"/preferred_username","groups":"/groups"}}}]}
          EOF

          echo "Configuring Yaade OIDC providers..."
          for i in $(seq 1 5); do
            http_code="$(curl -s -o /tmp/yaade-auth-response.json -w '%{http_code}' \
              -b /tmp/yaade-cookie \
              -H "Content-Type: application/json" \
              -X PUT \
              --data-binary @/tmp/yaade-auth.json \
              "${config_url}" || true)"
            if [ "${http_code}" = "200" ]; then
              echo "Yaade OIDC init complete."
              exit 0
            fi
            echo "Yaade OIDC init attempt ${i} failed (HTTP ${http_code})."
            if [ -s /tmp/yaade-auth-response.json ]; then
              cat /tmp/yaade-auth-response.json
            fi
            sleep 2
          done

          echo "Yaade OIDC init failed after retries."
          exit 1
      command:
        - /bin/sh
        - -c
      env:
        - name: YAADE_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: YAADE_ADMIN_USERNAME
              name: skyforge-config
        - name: YAADE_BASE_PATH
          valueFrom:
            configMapKeyRef:
              key: YAADE_BASE_PATH
              name: skyforge-config
        - name: SKYFORGE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: SKYFORGE_HOSTNAME
              name: skyforge-config
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/skyforge-ca.crt
      image: curlimages/curl:8.10.1
      name: yaade-oidc-init
      volumeMounts:
        - mountPath: /run/secrets
          name: run-secrets
          readOnly: true
        - mountPath: /etc/ssl/certs/skyforge-ca.crt
          name: skyforge-ca-cert
          subPath: skyforge-ca-cert
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: run-secrets
      projected:
        sources:
          - secret:
              items:
                - key: yaade-admin-password
                  path: yaade-admin-password
              name: yaade-admin-password
          - secret:
              items:
                - key: skyforge-oidc-discovery-url
                  path: skyforge-oidc-discovery-url
              name: skyforge-oidc-discovery-url
          - secret:
              items:
                - key: dex-client-yaade-secret
                  path: dex-client-yaade-secret
              name: dex-client-yaade-secret
          - secret:
              items:
                - key: yaade-oidc-client-id
                  path: yaade-oidc-client-id
              name: yaade-oidc-client-id
    - name: skyforge-ca-cert
      secret:
        secretName: skyforge-ca-cert
