apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: yaade
  name: yaade
spec:
  ports:
    - name: web
      port: 80
      targetPort: 9339
  selector:
    io.kompose.service: yaade
