{{- $vals := fromYaml (toYaml .Values) -}}
{{- if .Values.skyforge.clabernetes.enabled -}}
{{- $install := dig "skyforge" "clabernetes" "cniPlugins" "install" true $vals -}}
{{- if $install -}}
{{- $ns := dig "skyforge" "clabernetes" "cniPlugins" "namespace" "kube-system" $vals -}}
{{- $version := dig "skyforge" "clabernetes" "cniPlugins" "version" "v1.5.1" $vals -}}
{{- $image := dig "skyforge" "clabernetes" "cniPlugins" "image" "alpine:3.20" $vals -}}
{{- $pullPolicy := dig "skyforge" "clabernetes" "cniPlugins" "imagePullPolicy" "IfNotPresent" $vals -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skyforge-cni-plugins
  namespace: {{ $ns | quote }}
  labels:
    app: skyforge-cni-plugins
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: skyforge-cni-plugins
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skyforge-cni-plugins
        {{- include "skyforge.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      initContainers:
        - name: install-cni-plugins
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pullPolicy | quote }}
          command:
            - /bin/sh
            - -lc
            - |
              set -euo pipefail
              apk add --no-cache curl tar >/dev/null

              # Only install if required binaries are missing.
              required="bridge host-local macvlan ipvlan"
              missing="0"
              for b in $required; do
                if [ ! -x "/host/opt/cni/bin/$b" ]; then
                  missing="1"
                fi
              done

              if [ "$missing" = "0" ]; then
                echo "CNI plugins already installed."
                exit 0
              fi

              url="https://github.com/containernetworking/plugins/releases/download/{{ $version }}/cni-plugins-linux-amd64-{{ $version }}.tgz"
              echo "Downloading CNI plugins: $url"
              curl -fsSL "$url" -o /tmp/cni-plugins.tgz
              mkdir -p /tmp/cni-plugins
              tar -C /tmp/cni-plugins -xzf /tmp/cni-plugins.tgz

              for b in bridge host-local loopback ptp tuning macvlan ipvlan; do
                if [ -f "/tmp/cni-plugins/$b" ]; then
                  cp -f "/tmp/cni-plugins/$b" "/host/opt/cni/bin/$b"
                  chmod 0755 "/host/opt/cni/bin/$b"
                fi
              done

              echo "Installed CNI plugins to /host/opt/cni/bin."
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
      containers:
        - name: pause
          image: {{ .Values.images.alpine | quote }}
          command: ["/bin/sh","-lc","sleep 365d"]
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
{{- end -}}
{{- end -}}
