apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: coder
  name: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coder
  template:
    metadata:
      labels:
        io.kompose.service: coder
    spec:
      serviceAccountName: coder
      containers:
        - name: coder
          image: {{ .Values.images.coder | quote }}
          env:
            - name: CODER_HTTP_ADDRESS
              value: "0.0.0.0:7080"
            - name: CODER_BASE_PATH
              value: "/"
            - name: CODER_ACCESS_URL
              value: "https://{{ .Values.skyforge.hostname }}"
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-pg-connection-url
                  key: coder-pg-connection-url
            - name: CODER_OIDC_ISSUER_URL
              value: "https://{{ .Values.skyforge.hostname }}/dex-coder"
            - name: CODER_OIDC_CLIENT_ID
              value: "coder"
            - name: CODER_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dex-client-coder-secret
                  key: dex-client-coder-secret
            - name: CODER_OIDC_CA_CERT
              value: "/etc/ssl/certs/skyforge-ca.crt"
            - name: CODER_OIDC_AUTO_LOGIN
              value: {{ .Values.skyforge.coder.oidcAutoLogin | quote }}
            - name: CODER_DISABLE_PASSWORD_AUTH
              value: {{ .Values.skyforge.coder.disablePasswordAuth | quote }}
            - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
              value: "false"
          ports:
            - containerPort: 7080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/lib/coder
              name: coder-data
            - mountPath: /etc/ssl/certs/skyforge-ca.crt
              name: skyforge-ca-cert
              subPath: skyforge-ca-cert
              readOnly: true
      volumes:
        - name: coder-data
          persistentVolumeClaim:
            claimName: coder-data
        - name: skyforge-ca-cert
          secret:
            secretName: skyforge-ca-cert
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: coder
  name: coder
spec:
  ports:
    - name: http
      port: 7080
      targetPort: 7080
  selector:
    io.kompose.service: coder
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: coder-data
  name: coder-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
