{{- if .Values.skyforge.coder.enabled -}}
{{- $coderDBPassword := include "skyforge.secretOrValue" (list . "db-coder-password" "db-coder-password" (index (index .Values.secrets.items "db-coder-password") "db-coder-password" | default "coder")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: coder-pg-connection-url
  annotations:
    "helm.sh/resource-policy": keep
  labels:
{{ include "skyforge.labels" . | indent 4 }}
type: Opaque
stringData:
  coder-pg-connection-url: {{ printf "postgres://coder:%s@db:5432/coder?sslmode=disable" $coderDBPassword | quote }}
{{- end }}
