apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder
  labels:
{{ include "skyforge.labels" . | indent 4 }}
{{- $pullSecrets := .Values.kubernetes.imagePullSecrets -}}
{{- if $pullSecrets }}
imagePullSecrets:
{{- range $name := $pullSecrets }}
  - name: {{ $name | quote }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder
  labels:
{{ include "skyforge.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/exec
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder
  labels:
{{ include "skyforge.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder
subjects:
  - kind: ServiceAccount
    name: coder
