{{- if .Values.kubernetes.imagePullSecrets }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  labels:
{{ include "skyforge.labels" . | indent 4 }}
imagePullSecrets:
{{- range .Values.kubernetes.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}

