{{- if .Values.skyforge.coder.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-coder-config-template
data:
  render.py: |
    import os
    from pathlib import Path
    import textwrap

    hostname = os.environ.get("SKYFORGE_HOSTNAME", "").strip()
    if not hostname:
        raise SystemExit("SKYFORGE_HOSTNAME is required")

    secret_path = Path("/run/secrets/dex-client-coder-secret/dex-client-coder-secret")
    client_secret = secret_path.read_text(encoding="utf-8").strip()
    if not client_secret:
        raise SystemExit("dex-client-coder-secret is empty")

    out = Path("/etc/dex/config.yaml")
    out.parent.mkdir(parents=True, exist_ok=True)

    config = textwrap.dedent(
        f"""
        issuer: https://{hostname}/dex-coder
        storage:
          type: memory
        web:
          http: 0.0.0.0:5556
        oauth2:
          skipApprovalScreen: true
          alwaysShowLoginScreen: false
        connectors:
          - type: authproxy
            id: authproxy
            name: Skyforge
            config:
              userHeader: Remote-User
              emailHeader: Remote-User-Email
              groupsHeader: X-Skyforge-Groups
        staticClients:
          - id: coder
            name: Coder
            secret: {client_secret}
            redirectURIs:
              - https://{hostname}/api/v2/users/oidc/callback
              - https://{hostname}/coder/oauth2/callback
        """
    ).lstrip()
    out.write_text(config, encoding="utf-8")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dex-coder
  name: dex-coder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dex-coder
  template:
    metadata:
      labels:
        io.kompose.service: dex-coder
    spec:
      initContainers:
        - name: render-config
          image: {{ .Values.images.python | quote }}
          env:
            - name: SKYFORGE_HOSTNAME
              value: {{ .Values.skyforge.hostname | quote }}
          command: ["python", "/config/render.py"]
          volumeMounts:
            - name: config-template
              mountPath: /config
              readOnly: true
            - name: dex-coder-config
              mountPath: /etc/dex
            - name: dex-client-coder-secret
              mountPath: /run/secrets/dex-client-coder-secret
              readOnly: true
      containers:
        - name: dex
          image: {{ .Values.images.dex | quote }}
          command: ["dex"]
          args: ["serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: dex-coder-config
              mountPath: /etc/dex
              readOnly: true
      volumes:
        - name: config-template
          configMap:
            name: dex-coder-config-template
        - name: dex-coder-config
          emptyDir: {}
        - name: dex-client-coder-secret
          secret:
            secretName: dex-client-coder-secret
            items:
              - key: dex-client-coder-secret
                path: dex-client-coder-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dex-coder
  name: dex-coder
spec:
  ports:
    - name: http
      port: 5556
      targetPort: 5556
  selector:
    io.kompose.service: dex-coder
{{- end }}
