{{- if .Values.skyforge.dex.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dex
  template:
    metadata:
      annotations:
        checksum/dex-config: {{ include (print $.Template.BasePath "/dex-config-secret.yaml") . | sha256sum }}
        checksum/dex-config-patcher: {{ include (print $.Template.BasePath "/dex-config-patcher.yaml") . | sha256sum }}
      labels:
        io.kompose.service: dex
    spec:
      initContainers:
        - name: patch-config
          image: {{ .Values.images.python | quote }}
          env:
            - name: DEX_WEB_THEME
              value: {{ .Values.skyforge.dex.webTheme | default "" | quote }}
            - name: DEX_LOGO_URL
              value: {{ .Values.skyforge.dex.logoUrl | default "" | quote }}
            - name: DEX_OKTA_ENABLED
              value: {{ ternary "true" "false" (default false .Values.skyforge.dex.okta.enabled) | quote }}
{{- if (default false .Values.skyforge.dex.okta.enabled) }}
            - name: DEX_OKTA_NAME
              value: {{ default "Okta" .Values.skyforge.dex.okta.name | quote }}
            - name: DEX_OKTA_ISSUER
              value: {{ default "" .Values.skyforge.dex.okta.issuer | quote }}
            - name: DEX_OKTA_CLIENT_ID
              value: {{ default "" .Values.skyforge.dex.okta.clientID | quote }}
            - name: DEX_OKTA_SCOPES
              value: {{ join "," (default (list) .Values.skyforge.dex.okta.scopes) | quote }}
            - name: DEX_OKTA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default "dex-okta-client-secret" .Values.skyforge.dex.okta.clientSecretSecretName | quote }}
                  key: {{ default "dex-okta-client-secret" .Values.skyforge.dex.okta.clientSecretSecretKey | quote }}
{{- end }}
          command:
            - sh
            - -c
            - python -m pip install --no-cache-dir pyyaml >/dev/null && python /config/patch.py
          volumeMounts:
            - name: dex-config-template
              mountPath: /config
              readOnly: true
            - name: dex-config-src
              mountPath: /etc/dex-src
              readOnly: true
            - name: dex-config
              mountPath: /etc/dex
      containers:
        - name: dex
          image: {{ .Values.images.dex | quote }}
          command: ["dex"]
          args: ["serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: dex-config
              mountPath: /etc/dex
              readOnly: true
            - name: dex-data
              mountPath: /var/dex
      volumes:
        - name: dex-config
          emptyDir: {}
        - name: dex-data
          emptyDir: {}
        - name: dex-config-src
          secret:
            secretName: dex-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: dex-config-template
          configMap:
            name: dex-config-patcher
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  ports:
    - name: http
      port: 5556
      targetPort: 5556
  selector:
    io.kompose.service: dex
{{- end }}
