{{- if .Values.skyforge.dex.enabled -}}
{{- $dexConfigChecksum := "" -}}
{{- if .Values.skyforge.dex.manageConfig -}}
  {{- $dexConfigChecksum = (include (print $.Template.BasePath "/dex-config-secret.yaml") . | sha256sum) -}}
{{- else -}}
  {{- $dexConfigValue := "" -}}
  {{- $dexConfigSecret := lookup "v1" "Secret" .Release.Namespace "dex-config" -}}
  {{- if and $dexConfigSecret (index $dexConfigSecret.data "config.yaml") -}}
    {{- $dexConfigValue = ((index $dexConfigSecret.data "config.yaml") | b64dec) -}}
  {{- else if and .Values.secrets .Values.secrets.items -}}
    {{- $dexConfig := (index .Values.secrets.items "dex-config") -}}
    {{- if $dexConfig -}}
      {{- $dexConfigValue = (index $dexConfig "config.yaml" | default "") -}}
    {{- end -}}
  {{- end -}}
  {{- $dexConfigChecksum = ($dexConfigValue | sha256sum) -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dex
  name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dex
  template:
    metadata:
      annotations:
        checksum/dex-config: {{ $dexConfigChecksum }}
        checksum/dex-config-patcher: {{ include (print $.Template.BasePath "/dex-config-patcher.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: dex
    spec:
      initContainers:
        - name: patch-config
          image: {{ .Values.images.python | quote }}
          env:
            - name: DEX_WEB_THEME
              value: {{ .Values.skyforge.dex.webTheme | default "" | quote }}
            - name: DEX_LOGO_URL
              value: {{ .Values.skyforge.dex.logoUrl | default "" | quote }}
          command:
            - sh
            - -c
            - python /config/patch.py
          volumeMounts:
            - name: dex-config-template
              mountPath: /config
              readOnly: true
            - name: dex-config-src
              mountPath: /etc/dex-src
              readOnly: true
            - name: dex-config
              mountPath: /etc/dex
      containers:
        - name: dex
          image: {{ .Values.images.dex | quote }}
          command: ["dex"]
          args: ["serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: dex-config
              mountPath: /etc/dex
              readOnly: true
            - name: dex-data
              mountPath: /var/dex
      volumes:
        - name: dex-config
          emptyDir: {}
        - name: dex-data
          emptyDir: {}
        - name: dex-config-src
          secret:
            secretName: dex-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: dex-config-template
          configMap:
            name: dex-config-patcher
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dex
  name: dex
spec:
  ports:
    - name: http
      port: 5556
      targetPort: 5556
  selector:
    app.kubernetes.io/name: dex
{{- end }}
