{{- if .Values.skyforge.dex.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dex
  template:
    metadata:
      annotations:
        checksum/dex-config: {{ include (print $.Template.BasePath "/dex-config-secret.yaml") . | sha256sum }}
      labels:
        io.kompose.service: dex
    spec:
      {{- /*
      Dex config patching used to install Python deps at runtime, which fails in
      clusters without outbound internet access. Instead:
      - When manageConfig=true, Helm renders the full Dex config Secret.
      - When manageConfig=false, we simply copy the existing Secret into the
        expected path.
      */ -}}
      {{- if not .Values.skyforge.dex.manageConfig }}
      initContainers:
        - name: patch-config
          image: {{ .Values.images.python | quote }}
          command: ["sh", "-c", "cp /etc/dex-src/config.yaml /etc/dex/config.yaml"]
          volumeMounts:
            - name: dex-config-src
              mountPath: /etc/dex-src
              readOnly: true
            - name: dex-config
              mountPath: /etc/dex
      {{- end }}
      containers:
        - name: dex
          image: {{ .Values.images.dex | quote }}
          command: ["dex"]
          args: ["serve", "/etc/dex/config.yaml"]
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: dex-config
              mountPath: /etc/dex
              readOnly: true
            - name: dex-data
              mountPath: /var/dex
      volumes:
        - name: dex-config
          emptyDir: {}
        - name: dex-data
          emptyDir: {}
        - name: dex-config-src
          secret:
            secretName: dex-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dex
  name: dex
spec:
  ports:
    - name: http
      port: 5556
      targetPort: 5556
  selector:
    io.kompose.service: dex
{{- end }}
