{{- $elastic := (get .Values.skyforge "elastic" | default (dict)) -}}
{{- $autosleep := (get $elastic "autosleep" | default (dict)) -}}
{{- if and (get $elastic "enabled" | default false) (get $autosleep "enabled" | default false) -}}
{{- $curlCmd := "curl --fail-with-body -sS --retry 3 --retry-delay 2 -X POST -H \"X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}\"" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-elastic-autosleep
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: {{ (get $autosleep "schedule" | default "*/5 * * * *") | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 55
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl
              image: {{ .Values.images.curl | quote }}
              imagePullPolicy: IfNotPresent
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
              command: ["sh", "-c"]
              args:
                - {{ printf "%s http://skyforge-server:8085/internal/elastic/tools/autosleep-tick" $curlCmd | quote }}
{{- end -}}

