{{- if .Values.skyforge.encoreCfg.workerCreate }}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg-worker
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `skyforge` service (worker deployment).
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_SKYFORGE: {{ .Values.skyforge.encoreCfg.workerJson | trim | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}

