{{- if .Values.skyforge.encoreCfg.workerCreate }}
{{- $cfg := dict -}}
{{- if .Values.skyforge.encoreCfg.workerJson }}
{{- $cfg = (fromJson (.Values.skyforge.encoreCfg.workerJson | trim)) -}}
{{- end }}
{{- $_ := set $cfg "TaskWorkerEnabled" true -}}
{{- $netlabGenerator := merge (get $cfg "NetlabGenerator" | default (dict)) (dict
  "C9sGeneratorMode" "k8s"
  "GeneratorImage" (default "" .Values.skyforge.netlabC9s.generatorImage)
  "PullPolicy" (default "" .Values.skyforge.netlabC9s.generatorPullPolicy)
) -}}
{{- $_ := set $cfg "NetlabGenerator" $netlabGenerator -}}
{{- $forward := merge (get $cfg "Forward" | default (dict)) (dict
  "SNMPPlaceholderEnabled" (default true .Values.skyforge.forward.snmpPlaceholderEnabled)
  "SNMPCommunity" (default "public" .Values.skyforge.forward.snmpCommunity)
) -}}
{{- $_ := set $cfg "Forward" $forward -}}
{{- $_ := set $cfg "NotificationsEnabled" (default true .Values.skyforge.notificationsEnabled) -}}
{{- $_ := set $cfg "StaticRoot" (default "/opt/skyforge/static" .Values.skyforge.staticRoot) -}}
{{- $_ := set $cfg "ListenAddr" (default ":8085" .Values.skyforge.listenAddr) -}}
{{- $_ := set $cfg "AdminUsers" (default "" .Values.skyforge.adminUsers) -}}
{{- $_ := set $cfg "AdminUsername" (default "skyforge" .Values.skyforge.admin.username) -}}
{{- $_ := set $cfg "CorpEmailDomain" (default "" .Values.skyforge.domain) -}}
{{- $_ := set $cfg "MaxGroups" (default 50 .Values.skyforge.maxGroups) -}}
{{- $_ := set $cfg "SessionCookie" (default "skyforge_session" .Values.skyforge.sessionCookie) -}}
{{- $_ := set $cfg "SessionTTL" (default "8h" .Values.skyforge.sessionTtl) -}}
{{- $_ := set $cfg "CookieSecure" (printf "%v" (default true .Values.skyforge.cookieSecure)) -}}
{{- $_ := set $cfg "CookieDomain" (default "" .Values.skyforge.cookieDomain) -}}
{{- $_ := set $cfg "PKIDefaultDays" (default 365 .Values.skyforge.pkiDefaultDays) -}}
{{- $_ := set $cfg "SSHCADefaultDays" (default 30 .Values.skyforge.sshDefaultDays) -}}
{{- $oidc := merge (get $cfg "OIDC" | default (dict)) (dict
  "DiscoveryURL" (default "http://dex:5556/dex" .Values.skyforge.oidc.discoveryUrl)
  "IssuerURL" (printf "https://%s/dex" .Values.skyforge.hostname)
  "RedirectURL" (printf "https://%s/api/skyforge/api/oidc/callback" .Values.skyforge.hostname)
) -}}
{{- $_ := set $cfg "OIDC" $oidc -}}
{{- $_ := set $cfg "PublicURL" (default (default "" .Values.skyforge.labsPublicUrl) .Values.skyforge.publicUrl | trimSuffix "/") -}}
{{- $_ := set $cfg "AwsSSOStartURL" (default "" .Values.skyforge.awsSsoStartUrl) -}}
{{- $_ := set $cfg "AwsSSORegion" (default "us-east-1" .Values.skyforge.awsSsoRegion) -}}
{{- $_ := set $cfg "YaadeAdminUsername" (default "admin" .Values.skyforge.yaadeAdminUsername) -}}
{{- $ldap := merge (get $cfg "LDAP" | default (dict)) (dict
  "BaseDN" (default "" .Values.skyforge.ldap.baseDn)
  "DisplayNameAttr" (default "" .Values.skyforge.ldap.displayAttr)
  "MailAttr" (default "" .Values.skyforge.ldap.mailAttr)
  "GroupAttr" (default "" .Values.skyforge.ldap.groupAttr)
  "UseStartTLS" (default false .Values.skyforge.ldap.startTls)
  "SkipTLSVerify" (default false .Values.skyforge.ldap.skipTlsVerify)
) -}}
{{- $_ := set $cfg "LDAP" $ldap -}}
{{- $dns := merge (get $cfg "DNS" | default (dict)) (dict
  "AdminUsername" (default "admin" .Values.skyforge.dns.adminUsername)
  "UserZoneSuffix" (default "skyforge" .Values.skyforge.dns.userZoneSuffix)
) -}}
{{- $_ := set $cfg "DNS" $dns -}}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg-worker
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `worker` service.
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_WORKER: {{ toJson $cfg | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}
