{{- if .Values.skyforge.encoreCfg.workerCreate }}
{{- $cfg := dict -}}
{{- if .Values.skyforge.encoreCfg.workerJson }}
{{- $cfg = (fromJson (.Values.skyforge.encoreCfg.workerJson | trim)) -}}
{{- end }}
{{- $_ := set $cfg "TaskWorkerEnabled" true -}}
{{- $netlabGenerator := merge (get $cfg "NetlabGenerator" | default (dict)) (dict
  "C9sGeneratorMode" "k8s"
  "GeneratorImage" (default "" .Values.skyforge.netlabC9s.generatorImage)
  "PullPolicy" (default "" .Values.skyforge.netlabC9s.generatorPullPolicy)
  "AnsibleImage" (default "" .Values.skyforge.netlabC9s.ansibleImage)
  "AnsiblePullPolicy" (default "" .Values.skyforge.netlabC9s.ansiblePullPolicy)
) -}}
{{- $_ := set $cfg "NetlabGenerator" $netlabGenerator -}}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg-worker
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `worker` service.
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_WORKER: {{ toJson $cfg | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}
