{{- if .Values.skyforge.encoreCfg.workerCreate }}
{{- $cfg := dict -}}
{{- if .Values.skyforge.encoreCfg.workerJson }}
{{- $cfg = (fromJson (.Values.skyforge.encoreCfg.workerJson | trim)) -}}
{{- end }}
{{- $_ := set $cfg "TaskWorkerEnabled" true -}}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg-worker
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `skyforge` service (worker deployment).
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_SKYFORGE: {{ toJson $cfg | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}
