{{- if .Values.skyforge.encoreCfg.create }}
{{- $cfg := dict -}}
{{- if .Values.skyforge.encoreCfg.json }}
{{- $cfg = (fromJson (.Values.skyforge.encoreCfg.json | trim)) -}}
{{- end }}
{{- $integrations := merge (get $cfg "Integrations" | default (dict)) (dict
  "GiteaBaseURL" (default "" .Values.skyforge.gitea.url | trimSuffix "/")
  "NetboxBaseURL" (default "" .Values.skyforge.netboxUrl | trimSuffix "/")
  "NautobotBaseURL" (default "" .Values.skyforge.nautobotUrl | trimSuffix "/")
  "YaadeBaseURL" (default "" .Values.skyforge.yaadeUrl | trimSuffix "/")
) -}}
{{- $_ := set $cfg "Integrations" $integrations -}}
{{- $netlab := merge (get $cfg "Netlab" | default (dict)) (dict
  "SSHUser" (default "" .Values.skyforge.netlab.sshUser)
  "StateRoot" (default "" .Values.skyforge.netlab.stateRoot)
) -}}
{{- $_ := set $cfg "Netlab" $netlab -}}
{{- $_ := set $cfg "PublicURL" (default (default "" .Values.skyforge.labsPublicUrl) .Values.skyforge.publicUrl | trimSuffix "/") -}}
{{- $workspaces := merge (get $cfg "Workspaces" | default (dict)) (dict
  "DataDir" (default "/var/lib/skyforge" .Values.skyforge.workspacesDataDir)
  "GiteaAPIURL" (default "" .Values.skyforge.gitea.apiUrl | trimSuffix "/")
  "GiteaUsername" (default "" .Values.skyforge.gitea.username)
  "GiteaRepoPrivate" (default true .Values.skyforge.gitea.repoPrivate)
  "DeleteMode" (default "live" .Values.skyforge.workspaceDeleteMode)
) -}}
{{- $_ := set $cfg "Workspaces" $workspaces -}}
{{- $objectStorage := merge (get $cfg "ObjectStorage" | default (dict)) (dict
  "Endpoint" (default "minio:9000" .Values.skyforge.objectStorage.endpoint | trimSuffix "/")
  "UseSSL" (default false .Values.skyforge.objectStorage.useSsl)
) -}}
{{- $_ := set $cfg "ObjectStorage" $objectStorage -}}
{{- $terraform := merge (get $cfg "Terraform" | default (dict)) (dict
  "BinaryPath" (default "" .Values.skyforge.terraform.path)
  "Version" (default "" .Values.skyforge.terraform.version)
  "URL" (default "" .Values.skyforge.terraform.url)
) -}}
{{- $_ := set $cfg "Terraform" $terraform -}}
{{- $forward := merge (get $cfg "Forward" | default (dict)) (dict
  "SNMPPlaceholderEnabled" (default true .Values.skyforge.forward.snmpPlaceholderEnabled)
  "SNMPCommunity" (default "public" .Values.skyforge.forward.snmpCommunity)
) -}}
{{- $_ := set $cfg "Forward" $forward -}}
{{- $forwardCollectorMultusNetworks := (default (list) .Values.skyforge.forwardCollector.multusNetworks) -}}
{{- $vrnetlabMgmtVxlanEnabled := dig "skyforge" "clabernetes" "vrnetlabMgmtVxlan" "enabled" false (fromYaml (toYaml .Values)) -}}
{{- if and $vrnetlabMgmtVxlanEnabled (eq (len $forwardCollectorMultusNetworks) 0) -}}
{{- $forwardCollectorMultusNetworks = list "kube-system/vrnetlab-mgmt" -}}
{{- end -}}
{{- $forwardCollector := merge (get $cfg "ForwardCollector" | default (dict)) (dict
  "Image" (default "" .Values.skyforge.forwardCollector.image)
  "PullPolicy" (default "IfNotPresent" .Values.skyforge.forwardCollector.pullPolicy)
  "ImagePullSecretName" (default "" .Values.skyforge.forwardCollector.imagePullSecretName)
  "ImagePullSecretNamespace" (default "" .Values.skyforge.forwardCollector.imagePullSecretNamespace)
  "HeapSizeGB" (default 0 .Values.skyforge.forwardCollector.heapSizeGB)
  "MultusNetworks" $forwardCollectorMultusNetworks
) -}}
{{- $_ := set $cfg "ForwardCollector" $forwardCollector -}}
{{- $netlabGenerator := merge (get $cfg "NetlabGenerator" | default (dict)) (dict
  "C9sGeneratorMode" "k8s"
  "GeneratorImage" (default "" .Values.skyforge.netlabC9s.generatorImage)
  "PullPolicy" (default "" .Values.skyforge.netlabC9s.generatorPullPolicy)
) -}}
{{- $_ := set $cfg "NetlabGenerator" $netlabGenerator -}}
{{- $_ := set $cfg "TaskWorkerEnabled" true -}}
{{- $_ := set $cfg "NotificationsEnabled" (default true .Values.skyforge.notificationsEnabled) -}}
{{- $_ := set $cfg "StaticRoot" (default "/opt/skyforge/static" .Values.skyforge.staticRoot) -}}
{{- $_ := set $cfg "ListenAddr" (default ":8085" .Values.skyforge.listenAddr) -}}
{{- $_ := set $cfg "AdminUsers" (default "" .Values.skyforge.adminUsers) -}}
{{- $_ := set $cfg "AdminUsername" (default "skyforge" .Values.skyforge.admin.username) -}}
{{- $_ := set $cfg "CorpEmailDomain" (default "" .Values.skyforge.domain) -}}
{{- $_ := set $cfg "MaxGroups" (default 50 .Values.skyforge.maxGroups) -}}
{{- $_ := set $cfg "SessionCookie" (default "skyforge_session" .Values.skyforge.sessionCookie) -}}
{{- $_ := set $cfg "SessionTTL" (default "8h" .Values.skyforge.sessionTtl) -}}
{{- $_ := set $cfg "CookieSecure" (printf "%v" (default true .Values.skyforge.cookieSecure)) -}}
{{- $_ := set $cfg "CookieDomain" (default "" .Values.skyforge.cookieDomain) -}}
{{- $_ := set $cfg "PKIDefaultDays" (default 365 .Values.skyforge.pkiDefaultDays) -}}
{{- $_ := set $cfg "SSHCADefaultDays" (default 30 .Values.skyforge.sshDefaultDays) -}}
{{- $ui := merge (get $cfg "UI" | default (dict)) (dict
  "ProductName" (default "" .Values.skyforge.ui.productName)
  "ProductSubtitle" (default "" .Values.skyforge.ui.productSubtitle)
  "LogoURL" (default "" .Values.skyforge.ui.logoUrl)
  "LogoAlt" (default "" .Values.skyforge.ui.logoAlt)
  "HeaderBackground" (default "" .Values.skyforge.ui.headerBgUrl)
  "SupportText" (default "" .Values.skyforge.ui.supportText)
  "SupportURL" (default "" .Values.skyforge.ui.supportUrl)
  "ThemeDefault" (default "" .Values.skyforge.uiThemeDefault)
) -}}
{{- $_ := set $cfg "UI" $ui -}}
{{- $oidc := merge (get $cfg "OIDC" | default (dict)) (dict
  "DiscoveryURL" (default "http://dex:5556/dex" .Values.skyforge.oidc.discoveryUrl)
  "IssuerURL" (printf "https://%s/dex" .Values.skyforge.hostname)
  "RedirectURL" (printf "https://%s/api/skyforge/api/oidc/callback" .Values.skyforge.hostname)
) -}}
{{- $_ := set $cfg "OIDC" $oidc -}}
{{- $_ := set $cfg "AwsSSOStartURL" (default "" .Values.skyforge.awsSsoStartUrl) -}}
{{- $_ := set $cfg "AwsSSORegion" (default "us-east-1" .Values.skyforge.awsSsoRegion) -}}
{{- $_ := set $cfg "YaadeAdminUsername" (default "admin" .Values.skyforge.yaadeAdminUsername) -}}
{{- $ldap := merge (get $cfg "LDAP" | default (dict)) (dict
  "BaseDN" (default "" .Values.skyforge.ldap.baseDn)
  "DisplayNameAttr" (default "" .Values.skyforge.ldap.displayAttr)
  "MailAttr" (default "" .Values.skyforge.ldap.mailAttr)
  "GroupAttr" (default "" .Values.skyforge.ldap.groupAttr)
  "UseStartTLS" (default false .Values.skyforge.ldap.startTls)
  "SkipTLSVerify" (default false .Values.skyforge.ldap.skipTlsVerify)
) -}}
{{- $_ := set $cfg "LDAP" $ldap -}}
{{- $dns := merge (get $cfg "DNS" | default (dict)) (dict
  "AdminUsername" (default "admin" .Values.skyforge.dns.adminUsername)
  "UserZoneSuffix" (default "skyforge" .Values.skyforge.dns.userZoneSuffix)
) -}}
{{- $_ := set $cfg "DNS" $dns -}}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `skyforge` service.
  # Encore expects ENCORE_CFG_<SERVICE> to contain a base64url-encoded JSON object.
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_SKYFORGE: {{ toJson $cfg | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}
