{{- if .Values.skyforge.encoreCfg.create }}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `skyforge` service.
  # Encore expects ENCORE_CFG_<SERVICE> to contain a base64url-encoded JSON object.
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_SKYFORGE: {{ .Values.skyforge.encoreCfg.json | trim | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}

