{{- if .Values.skyforge.encoreCfg.create }}
{{- $cfg := dict -}}
{{- if .Values.skyforge.encoreCfg.json }}
{{- $cfg = (fromJson (.Values.skyforge.encoreCfg.json | trim)) -}}
{{- end }}
{{- $integrations := merge (get $cfg "Integrations" | default (dict)) (dict
  "GiteaBaseURL" (default "" .Values.skyforge.gitea.url | trimSuffix "/")
  "NetboxBaseURL" (default "" .Values.skyforge.netboxUrl | trimSuffix "/")
  "NautobotBaseURL" (default "" .Values.skyforge.nautobotUrl | trimSuffix "/")
  "YaadeBaseURL" (default "" .Values.skyforge.yaadeUrl | trimSuffix "/")
) -}}
{{- $_ := set $cfg "Integrations" $integrations -}}
{{- $netlab := merge (get $cfg "Netlab" | default (dict)) (dict
  "SSHUser" (default "" .Values.skyforge.netlab.sshUser)
  "StateRoot" (default "" .Values.skyforge.netlab.stateRoot)
) -}}
{{- $_ := set $cfg "Netlab" $netlab -}}
{{- $labs := merge (get $cfg "Labs" | default (dict)) (dict
  "EveSSHUser" (default "" .Values.skyforge.eveSshUser)
  "EveSSHTunnel" (default true .Values.skyforge.eveSshTunnelEnabled)
) -}}
{{- $_ := set $cfg "Labs" $labs -}}
{{- $labpp := merge (get $cfg "Labpp" | default (dict)) (dict
  "RunnerImage" (default "" .Values.skyforge.labpp.runnerImage)
  "RunnerPullPolicy" (default "" .Values.skyforge.labpp.runnerPullPolicy)
  "RunnerPVCName" (default "" .Values.skyforge.labpp.runnerPvc)
  "ConfigDirBase" (default "" .Values.skyforge.labpp.configDirBase)
  "ConfigVersion" (default "" .Values.skyforge.labpp.configVersion)
  "NetboxURL" (default "" .Values.skyforge.labpp.netboxUrl | trimSuffix "/")
  "NetboxMgmtSubnet" (default "" .Values.skyforge.labpp.netboxMgmtSubnet)
  "S3Region" (default "" .Values.skyforge.labpp.s3Region)
  "S3BucketName" (default "" .Values.skyforge.labpp.s3Bucket)
  "S3Endpoint" (default "" .Values.skyforge.labpp.s3Endpoint | trimSuffix "/")
  "S3DisableSSL" (default true .Values.skyforge.labpp.s3DisableSsl)
  "S3DisableChecksum" (default false .Values.skyforge.labpp.s3DisableChecksum)
) -}}
{{- $_ := set $cfg "Labpp" $labpp -}}
{{- $netlabGenerator := merge (get $cfg "NetlabGenerator" | default (dict)) (dict
  "C9sGeneratorMode" "k8s"
  "GeneratorImage" (default "" .Values.skyforge.netlabC9s.generatorImage)
  "PullPolicy" (default "" .Values.skyforge.netlabC9s.generatorPullPolicy)
  "AnsibleImage" (default "" .Values.skyforge.netlabC9s.ansibleImage)
  "AnsiblePullPolicy" (default "" .Values.skyforge.netlabC9s.ansiblePullPolicy)
) -}}
{{- $_ := set $cfg "NetlabGenerator" $netlabGenerator -}}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `skyforge` service.
  # Encore expects ENCORE_CFG_<SERVICE> to contain a base64url-encoded JSON object.
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_SKYFORGE: {{ toJson $cfg | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}
