{{- if .Values.skyforge.encoreCfg.workerCreate }}
{{- $cfg := dict -}}
{{- if .Values.skyforge.encoreCfg.workerJson }}
{{- $cfg = (fromJson (.Values.skyforge.encoreCfg.workerJson | trim)) -}}
{{- end }}
{{- $_ := set $cfg "TaskWorkerEnabled" true -}}
{{- $integrations := merge (get $cfg "Integrations" | default (dict)) (dict
  "GiteaBaseURL" (default "" .Values.skyforge.gitea.url | trimSuffix "/")
  "NetboxBaseURL" (default "" .Values.skyforge.netboxUrl | trimSuffix "/")
  "NautobotBaseURL" (default "" .Values.skyforge.nautobotUrl | trimSuffix "/")
  "YaadeBaseURL" (default "" .Values.skyforge.yaadeUrl | trimSuffix "/")
) -}}
{{- $_ := set $cfg "Integrations" $integrations -}}
{{- $userDataDir := coalesce .Values.skyforge.userDataDir .Values.skyforge.scopesDataDir "/var/lib/skyforge" -}}
{{- $userDeleteMode := coalesce .Values.skyforge.userDeleteMode .Values.skyforge.scopeDeleteMode "live" -}}
{{- $scopes := merge (get $cfg "Scopes" | default (dict)) (dict
  "DataDir" $userDataDir
  "GiteaAPIURL" (default "" .Values.skyforge.gitea.apiUrl | trimSuffix "/")
  "GiteaUsername" (default "" .Values.skyforge.gitea.username)
  "GiteaRepoPrivate" .Values.skyforge.gitea.repoPrivate
  "DeleteMode" $userDeleteMode
) -}}
{{- $_ := set $cfg "Scopes" $scopes -}}
{{- $objectStorage := merge (get $cfg "ObjectStorage" | default (dict)) (dict
  "Endpoint" (default "minio:9000" .Values.skyforge.objectStorage.endpoint | trimSuffix "/")
  "UseSSL" (default false .Values.skyforge.objectStorage.useSsl)
) -}}
{{- $_ := set $cfg "ObjectStorage" $objectStorage -}}
{{- $terraform := merge (get $cfg "Terraform" | default (dict)) (dict
  "BinaryPath" (default "" .Values.skyforge.terraform.path)
  "Version" (default "" .Values.skyforge.terraform.version)
  "URL" (default "" .Values.skyforge.terraform.url)
) -}}
{{- $_ := set $cfg "Terraform" $terraform -}}
{{- $netlabGenerator := merge (get $cfg "NetlabGenerator" | default (dict)) (dict
  "C9sGeneratorMode" "k8s"
  "GeneratorImage" (default "ghcr.io/forwardnetworks/skyforge-netlab-generator:latest" .Values.skyforge.netlabC9s.generatorImage)
  "PullPolicy" (default "IfNotPresent" .Values.skyforge.netlabC9s.generatorPullPolicy)
  "ApplierImage" (default "ghcr.io/forwardnetworks/skyforge-netlab-applier:latest" .Values.skyforge.netlabC9s.applierImage)
  "ApplierPullPolicy" (default "IfNotPresent" .Values.skyforge.netlabC9s.applierPullPolicy)
) -}}
{{- $_ := set $cfg "NetlabGenerator" $netlabGenerator -}}
{{- $forward := merge (get $cfg "Forward" | default (dict)) (dict
  "SNMPPlaceholderEnabled" .Values.skyforge.forward.snmpPlaceholderEnabled
  "SNMPCommunity" (default "public" .Values.skyforge.forward.snmpCommunity)
) -}}
{{- $_ := set $cfg "Forward" $forward -}}
{{- $features := merge (get $cfg "Features" | default (dict)) (dict
  "GiteaEnabled" .Values.skyforge.gitea.enabled
  "MinioEnabled" .Values.skyforge.minio.enabled
  "DexEnabled" .Values.skyforge.dex.enabled
  "CoderEnabled" .Values.skyforge.coder.enabled
  "YaadeEnabled" .Values.skyforge.yaade.enabled
  "SwaggerUIEnabled" .Values.skyforge.swaggerUI.enabled
  "ForwardEnabled" .Values.skyforge.forward.enabled
  "NetboxEnabled" .Values.skyforge.netbox.enabled
  "NautobotEnabled" .Values.skyforge.nautobot.enabled
  "DNSEnabled" .Values.skyforge.dns.enabled
) -}}
{{- $_ := set $cfg "Features" $features -}}
{{- $_ := set $cfg "NotificationsEnabled" .Values.skyforge.notificationsEnabled -}}
{{- $_ := set $cfg "StaticRoot" (default "/opt/skyforge/static" .Values.skyforge.staticRoot) -}}
{{- $_ := set $cfg "ListenAddr" (default ":8085" .Values.skyforge.listenAddr) -}}
{{- $_ := set $cfg "AdminUsers" (default "" .Values.skyforge.adminUsers) -}}
{{- $_ := set $cfg "AdminUsername" (default "skyforge" .Values.skyforge.admin.username) -}}
{{- $_ := set $cfg "CorpEmailDomain" (default "" .Values.skyforge.domain) -}}
{{- $_ := set $cfg "MaxGroups" (default 50 .Values.skyforge.maxGroups) -}}
{{- $_ := set $cfg "SessionCookie" (default "skyforge_session" .Values.skyforge.sessionCookie) -}}
{{- $_ := set $cfg "SessionTTL" (default "8h" .Values.skyforge.sessionTtl) -}}
{{- $_ := set $cfg "CookieSecure" (printf "%v" .Values.skyforge.cookieSecure) -}}
{{- $_ := set $cfg "CookieDomain" (default "" .Values.skyforge.cookieDomain) -}}
{{- $_ := set $cfg "PKIDefaultDays" (default 365 .Values.skyforge.pkiDefaultDays) -}}
{{- $_ := set $cfg "SSHCADefaultDays" (default 30 .Values.skyforge.sshDefaultDays) -}}
{{- $oidc := merge (get $cfg "OIDC" | default (dict)) (dict
  "DiscoveryURL" (default "http://dex:5556/dex" .Values.skyforge.oidc.discoveryUrl)
  "IssuerURL" (printf "https://%s/dex" .Values.skyforge.hostname)
  "RedirectURL" (printf "https://%s/api/oidc/callback" .Values.skyforge.hostname)
) -}}
{{- $_ := set $cfg "OIDC" $oidc -}}
{{- $_ := set $cfg "PublicURL" (default (default "" .Values.skyforge.labsPublicUrl) .Values.skyforge.publicUrl | trimSuffix "/") -}}
{{- $_ := set $cfg "AwsSSOStartURL" (default "" .Values.skyforge.awsSsoStartUrl) -}}
{{- $_ := set $cfg "AwsSSORegion" (default "us-east-1" .Values.skyforge.awsSsoRegion) -}}
{{- $_ := set $cfg "YaadeAdminUsername" (default "admin" .Values.skyforge.yaadeAdminUsername) -}}
{{- $geminiRedirect := default "" .Values.skyforge.gemini.redirectURL -}}
{{- if and (not $geminiRedirect) (default "" .Values.skyforge.publicUrl) -}}
  {{- $geminiRedirect = printf "%s/api/user/integrations/gemini/callback" (trimSuffix "/" .Values.skyforge.publicUrl) -}}
{{- end -}}
{{- if and (not $geminiRedirect) (default "" .Values.skyforge.hostname) -}}
  {{- $geminiRedirect = printf "https://%s/api/user/integrations/gemini/callback" .Values.skyforge.hostname -}}
{{- end -}}
{{- $gemini := merge (get $cfg "Gemini" | default (dict)) (dict
  "Enabled" (default false .Values.skyforge.gemini.enabled)
  "ClientID" (default "" .Values.skyforge.gemini.clientID)
  "RedirectURL" (default "" $geminiRedirect)
  "ProjectID" (default "" .Values.skyforge.gemini.projectId)
  "Location" (default "us-central1" .Values.skyforge.gemini.location)
  "Model" (default "gemini-3.0-pro" .Values.skyforge.gemini.model)
  "FallbackModel" (default "gemini-3.0-flash" .Values.skyforge.gemini.fallbackModel)
) -}}
{{- $_ := set $cfg "Gemini" $gemini -}}
{{- $ai := merge (get $cfg "AI" | default (dict)) (dict
  "Enabled" (default false .Values.skyforge.ai.enabled)
) -}}
{{- $_ := set $cfg "AI" $ai -}}
{{- $ldap := merge (get $cfg "LDAP" | default (dict)) (dict
  "BaseDN" (default "" .Values.skyforge.ldap.baseDn)
  "DisplayNameAttr" (default "" .Values.skyforge.ldap.displayAttr)
  "MailAttr" (default "" .Values.skyforge.ldap.mailAttr)
  "GroupAttr" (default "" .Values.skyforge.ldap.groupAttr)
  "UseStartTLS" (default false .Values.skyforge.ldap.startTls)
  "SkipTLSVerify" (default false .Values.skyforge.ldap.skipTlsVerify)
) -}}
{{- $_ := set $cfg "LDAP" $ldap -}}
{{- $dns := merge (get $cfg "DNS" | default (dict)) (dict
  "AdminUsername" (default "admin" .Values.skyforge.dns.adminUsername)
  "UserZoneSuffix" (default "skyforge" .Values.skyforge.dns.userZoneSuffix)
) -}}
{{- $_ := set $cfg "DNS" $dns -}}
apiVersion: v1
kind: Secret
metadata:
  name: skyforge-encore-cfg-worker
type: Opaque
stringData:
  # NOTE: This is the typed Encore config payload for the `worker` service.
  # Encore expects ENCORE_CFG_<SERVICE> to contain a base64url-encoded JSON object
  # without padding. (Encore uses base64.RawURLEncoding.)
  # Keep it non-secret: do not include passwords/tokens here.
  ENCORE_CFG_WORKER: {{ toJson $cfg | b64enc | replace "+" "-" | replace "/" "_" | trimAll "=" | quote }}
{{- end }}
