{{- if .Values.skyforge.forwardCluster.enabled -}}
{{- $secretItems := default (dict) .Values.secrets.items -}}
{{- $forwardAppPassword := include "skyforge.secretOrValue" (list . "db-forward-app-password" "db-forward-app-password" (index (default (dict) (index $secretItems "db-forward-app-password")) "db-forward-app-password" | default "")) -}}
{{- $forwardFDBPassword := include "skyforge.secretOrValue" (list . "db-forward-fdb-password" "db-forward-fdb-password" (index (default (dict) (index $secretItems "db-forward-fdb-password")) "db-forward-fdb-password" | default "")) -}}
{{- if not $forwardAppPassword -}}
  {{- fail "db-forward-app-password.db-forward-app-password must be set when skyforge.forwardCluster.enabled=true" -}}
{{- end -}}
{{- if not $forwardFDBPassword -}}
  {{- fail "db-forward-fdb-password.db-forward-fdb-password must be set when skyforge.forwardCluster.enabled=true" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres.fwd-pg-app.credentials
  namespace: forward
  labels:
{{ include "skyforge.labels" . | indent 4 }}
type: Opaque
data:
  user: {{ b64enc "fwd_app" | quote }}
  password: {{ b64enc $forwardAppPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres.fwd-pg-fdb.credentials
  namespace: forward
  labels:
{{ include "skyforge.labels" . | indent 4 }}
type: Opaque
data:
  user: {{ b64enc "fwd_fdb" | quote }}
  password: {{ b64enc $forwardFDBPassword | quote }}
{{- end -}}
