{{- $cfg := (get .Values.skyforge "forwardApp" | default dict) -}}
{{- if (get $cfg "enabled" | default false) -}}
{{- $ns := .Release.Namespace -}}
{{- $envoyImage := default "envoyproxy/envoy:v1.31.2" .Values.images.envoy -}}
{{- $pathPrefix := (get $cfg "pathPrefix" | default "/fwd") -}}
{{- $upNs := (get $cfg "upstreamNamespace" | default "forward") -}}
{{- $upSvc := (get $cfg "upstreamService" | default "fwd-appserver") -}}
{{- $upPort := (get $cfg "upstreamPort" | default 8080) -}}
{{- $requireAuth := (get $cfg "requireAuth" | default true) -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forward-app-proxy-envoy
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

    static_resources:
      listeners:
        - name: listener_http
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    normalize_path: true
                    use_remote_address: true
                    stream_idle_timeout: 300s
                    upgrade_configs:
                      - upgrade_type: websocket
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: forward_app
                          domains: ["*"]
                          routes:
                            # Canonicalize /fwd -> /fwd/ (nice URLs and consistent relative paths).
                            - match:
                                path: {{ $pathPrefix | quote }}
                              redirect:
                                path_redirect: {{ printf "%s/" $pathPrefix | quote }}
                            - match:
                                prefix: {{ printf "%s/" $pathPrefix | quote }}
                              route:
                                cluster: forward_upstream
                                # Strip /fwd from incoming requests to the upstream.
                                prefix_rewrite: /
                                request_headers_to_add:
                                  - header:
                                      key: x-forwarded-prefix
                                      value: {{ $pathPrefix | quote }}
                                  - header:
                                      key: x-skyforge-external-prefix
                                      value: {{ $pathPrefix | quote }}
                    http_filters:
{{- if $requireAuth }}
                      - name: envoy.filters.http.ext_authz
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                          transport_api_version: V3
                          failure_mode_allow: false
                          http_service:
                            server_uri:
                              uri: http://skyforge-server.{{ $ns }}.svc.cluster.local:8085
                              cluster: skyforge_server
                              timeout: 2s
                            path_prefix: /api/session/forwardauth/envoy
                            authorization_request:
                              allowed_headers:
                                patterns:
                                  - exact: cookie
                                  - exact: x-forwarded-proto
                                  - exact: x-forwarded-host
                                  - exact: x-forwarded-for
                                  - exact: x-forwarded-uri
                                  - exact: x-forwarded-prefix
                                  - exact: user-agent
                                  - exact: accept
                                  - exact: accept-language
                                  - exact: x-skyforge-external-prefix
                            authorization_response:
                              allowed_upstream_headers:
                                patterns:
                                  - exact: remote-user
                                  - exact: remote-user-group
                                  - exact: remote-user-email
                                  - exact: remote-user-first-name
                                  - exact: remote-user-last-name
                                  - exact: x-forwarded-user
                                  - exact: x-forwarded-email
                                  - exact: x-forwarded-first-name
                                  - exact: x-forwarded-last-name
                              allowed_client_headers:
                                patterns:
                                  - exact: location
{{- end }}
                      # Best-effort: if the upstream returns absolute redirects (/login, /app, ...),
                      # re-prefix them so the browser stays under /fwd.
                      #
                      # Important: don't touch Skyforge login redirects (they start with /api/oidc/login).
                      - name: envoy.filters.http.lua
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                          inline_code: |
                            function envoy_on_response(handle)
                              local loc = handle:headers():get("location")
                              if loc == nil then
                                return
                              end
                              if string.sub(loc, 1, 1) ~= "/" then
                                return
                              end
                              if string.sub(loc, 1, 14) == "/api/oidc/login" then
                                return
                              end
                              if string.sub(loc, 1, {{ add (len $pathPrefix) 1 }}) == "{{ $pathPrefix }}/" or loc == "{{ $pathPrefix }}" then
                                return
                              end
                              handle:headers():replace("location", "{{ $pathPrefix }}" .. loc)
                            end

                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: skyforge_server
          type: STRICT_DNS
          connect_timeout: 2s
          load_assignment:
            cluster_name: skyforge_server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: skyforge-server.{{ $ns }}.svc.cluster.local
                          port_value: 8085

        - name: forward_upstream
          type: STRICT_DNS
          connect_timeout: 5s
          load_assignment:
            cluster_name: forward_upstream
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ $upSvc }}.{{ $upNs }}.svc.cluster.local
                          port_value: {{ $upPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-app-proxy
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forward-app-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forward-app-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: sso-proxy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: envoy
          image: {{ $envoyImage | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "/etc/envoy/envoy.yaml"
          ports:
            - name: http
              containerPort: 8080
            - name: admin
              containerPort: 9901
          readinessProbe:
            httpGet:
              path: /ready
              port: 9901
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ready
              port: 9901
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: envoy-conf
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-conf
          configMap:
            name: forward-app-proxy-envoy

---
apiVersion: v1
kind: Service
metadata:
  name: forward-app-proxy
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forward-app-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
{{- end }}

