{{- $host := .Values.skyforge.hostname -}}
{{- $giteaEnabled := .Values.skyforge.gitea.enabled -}}
{{- $yaadeEnabled := .Values.skyforge.yaade.enabled -}}
{{- $redocEnabled := .Values.skyforge.redoc.enabled -}}
{{- $dexEnabled := .Values.skyforge.dex.enabled -}}
{{- $coderEnabled := .Values.skyforge.coder.enabled -}}
{{- $filesBucket := .Values.skyforge.objectStorage.filesBucket | default "skyforge-files" -}}
{{- $gatewayAddresses := .Values.skyforge.gateway.addresses | default (list) -}}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: skyforge
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  gatewayClassName: cilium
  {{- if gt (len $gatewayAddresses) 0 }}
  addresses:
{{ toYaml $gatewayAddresses | nindent 4 }}
  {{- end }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: proxy-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: skyforge
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: skyforge
  hostnames:
    - {{ $host | quote }}
  rules:
    # Core Skyforge endpoints
    - matches:
        - path:
            type: PathPrefix
            value: /assets/skyforge/
      backendRefs:
        - name: skyforge-server
          port: 8085
    - matches:
        - path:
            type: PathPrefix
            value: /healthz
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: skyforge-server
          port: 8085

{{- if $dexEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /dex
      backendRefs:
        - name: dex
          port: 5556
{{- end }}

{{- if .Values.skyforge.forwardCluster.enabled }}
    - matches:
        - path:
            type: Exact
            value: /fwd
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /fwd/
    - matches:
        - path:
            type: PathPrefix
            value: /fwd/
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    # Forward upstream commonly redirects to /login. Route that back through
    # the Forward SSO proxy instead of falling through to Skyforge app routes.
    - matches:
        - path:
            type: Exact
            value: /login
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /login/
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    # Forward login UI serves frontend bundles under /app/assets/* and favicon at
    # /favicon.ico. Route these to the Forward SSO proxy to avoid white screens.
    - matches:
        - path:
            type: PathPrefix
            value: /app
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    - matches:
        - path:
            type: Exact
            value: /favicon.ico
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /img
        - path:
            type: PathPrefix
            value: /fonts
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    # Forward login frontend calls these APIs as /api/public/* (no /fwd prefix).
    # Route only the known Forward auth endpoints and keep Skyforge's own
    # /api/public/config on the Skyforge backend.
    - matches:
        - path:
            type: Exact
            value: /api/public/csrf
        - path:
            type: Exact
            value: /api/public/password-reset
        - path:
            type: Exact
            value: /api/public/password-strength
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    - matches:
        - path:
            type: Exact
            value: /api/backups
        - path:
            type: Exact
            value: /api/licenses
        - path:
            type: Exact
            value: /api/notifications
        - path:
            type: Exact
            value: /api/custom-banners
        - path:
            type: Exact
            value: /api/webhooks
        - path:
            type: Exact
            value: /api/licensed-devices
        - path:
            type: Exact
            value: /api/approved-cli-commands
        - path:
            type: Exact
            value: /api/global-config
        - path:
            type: Exact
            value: /api/config
        - path:
            type: PathPrefix
            value: /api/config/
        - path:
            type: Exact
            value: /api/timeZones
        - path:
            type: Exact
            value: /api/trusted-certificates
        - path:
            type: Exact
            value: /api/backup-settings
        - path:
            type: Exact
            value: /api/vm/admin/appUrl
        - path:
            type: Exact
            value: /api/critical-states
        - path:
            type: Exact
            value: /api/cve-index
        - path:
            type: Exact
            value: /api/feature-usage
        - path:
            type: Exact
            value: /api/metrics/usage-report
        - path:
            type: Exact
            value: /api/nqe
        - path:
            type: Exact
            value: /api/requests
        - path:
            type: Exact
            value: /api/stig-policy-template
        - path:
            type: Exact
            value: /api/unimpersonate
        - path:
            type: Exact
            value: /api/users/current
        - path:
            type: Exact
            value: /api/users/current/events
        - path:
            type: Exact
            value: /api/users/current/prefs
        - path:
            type: Exact
            value: /api/users/current/tokens
        - path:
            type: Exact
            value: /api/users/current/network-preferences
        - path:
            type: Exact
            value: /api/admin/impersonate
        - path:
            type: Exact
            value: /api/admin/networks
        - path:
            type: PathPrefix
            value: /api/admin/networks/
        - path:
            type: Exact
            value: /api/users
        - path:
            type: Exact
            value: /api/access-control-groups
        - path:
            type: Exact
            value: /api/device-access-labels
        - path:
            type: Exact
            value: /api/auth/tacacs-settings
        - path:
            type: Exact
            value: /api/auth/tacacs-tests
        - path:
            type: Exact
            value: /api/auth/ldap-settings
        - path:
            type: Exact
            value: /api/auth/ldap-tests
        - path:
            type: Exact
            value: /api/auth/saml-settings
        - path:
            type: Exact
            value: /api/auth/saml-tests
        - path:
            type: PathPrefix
            value: /api/collector-tasks
        - path:
            type: Exact
            value: /api/integrations/dns
        - path:
            type: Exact
            value: /api/integrations/infoblox
        - path:
            type: PathPrefix
            value: /api/integrations/infoblox/
        - path:
            type: Exact
            value: /api/integrations/slack
        - path:
            type: Exact
            value: /api/integrations/smtp
        - path:
            type: Exact
            value: /api/integrations/servicenow-cmdb/configuration
        - path:
            type: Exact
            value: /api/notifications/subscriptions
        - path:
            type: PathPrefix
            value: /api/config/alert_new_device_failure_percentage/overrides
        - path:
            type: PathPrefix
            value: /api/system/
        - path:
            type: PathPrefix
            value: /api/networks/
        - path:
            type: PathPrefix
            value: /api/snapshots/
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /release-notes/
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /fwd
              - name: X-Forwarded-Prefix
                value: /fwd
      backendRefs:
        - name: forward-sso-proxy
          port: 8080
{{- end }}
    # Root landing: / -> /index.html
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.html
      backendRefs:
        - name: skyforge-server
          port: 8085
    # SPA deep-link rewrite for settings routes.
    - matches:
        - path:
            type: Exact
            value: /settings
        - path:
            type: PathPrefix
            value: /settings/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.html
      backendRefs:
        - name: skyforge-server
          port: 8085

    # Default catch-all to Skyforge server
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: skyforge-server
          port: 8085
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: skyforge-tools
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: skyforge
  hostnames:
    - {{ $host | quote }}
  rules:
{{- if .Values.skyforge.s3gw.enabled }}
    # /files/* -> s3gw /<files-bucket>/*
    - matches:
        - path:
            type: PathPrefix
            value: /files/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: {{ printf "/%s/" $filesBucket }}
      backendRefs:
        - name: {{ .Values.skyforge.s3gw.serviceName }}
          port: {{ .Values.skyforge.s3gw.service.port }}
{{- end }}

{{- if $yaadeEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /api-testing
      backendRefs:
        - name: yaade
          port: 80
{{- end }}

{{- if .Values.skyforge.netbox.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /netbox/static/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /static/
      backendRefs:
        - name: netbox
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /netbox/media/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /media/
      backendRefs:
        - name: netbox
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /netbox
      backendRefs:
        - name: netbox-sso-proxy
          port: 8080
{{- end }}

{{- if .Values.skyforge.nautobot.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /nautobot
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Skyforge-External-Prefix
                value: /nautobot
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: nautobot-sso-proxy
          port: 8080
{{- end }}

{{- if $giteaEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /git
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /git
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: gitea-sso-proxy
          port: 8080
{{- end }}

{{- if $redocEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /redoc
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /redoc
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: redoc-sso-proxy
          port: 8080
{{- end }}

{{- if $coderEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /coder
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: coder
          port: 7080
    - matches:
        - path:
            type: PathPrefix
            value: /api/v2
      backendRefs:
        - name: coder
          port: 7080
{{- end }}

{{- if .Values.skyforge.dns.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /dns
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: technitium-dns
          port: 5380
{{- end }}
