{{- $host := .Values.skyforge.hostname -}}
{{- $giteaEnabled := .Values.skyforge.gitea.enabled -}}
{{- $yaadeEnabled := .Values.skyforge.yaade.enabled -}}
{{- $redocEnabled := .Values.skyforge.redoc.enabled -}}
{{- $dexEnabled := .Values.skyforge.dex.enabled -}}
{{- $coderEnabled := .Values.skyforge.coder.enabled -}}
{{- $filesBucket := .Values.skyforge.objectStorage.filesBucket | default "skyforge-files" -}}
{{- $gatewayAddresses := .Values.skyforge.gateway.addresses | default (list) -}}
{{- $forwardClusterEnabled := .Values.skyforge.forwardCluster.enabled -}}
{{- $forwardHost := default $host .Values.skyforge.forwardCluster.hostname -}}
{{- $forwardSvcName := default "fwd-appserver" .Values.skyforge.forwardCluster.serviceName -}}
{{- $forwardSvcNamespace := default "forward" .Values.skyforge.forwardCluster.serviceNamespace -}}
{{- $forwardSvcPort := default 8080 .Values.skyforge.forwardCluster.servicePort -}}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: skyforge
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  gatewayClassName: cilium
  {{- if gt (len $gatewayAddresses) 0 }}
  addresses:
{{ toYaml $gatewayAddresses | nindent 4 }}
  {{- end }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: proxy-tls
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: skyforge
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: skyforge
  hostnames:
    - {{ $host | quote }}
  rules:
    # Core Skyforge endpoints
    - matches:
        - path:
            type: PathPrefix
            value: /assets/skyforge/
      backendRefs:
        - name: skyforge-server
          port: 8085
    - matches:
        - path:
            type: PathPrefix
            value: /healthz
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: skyforge-server
          port: 8085

{{- if $dexEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /dex
      backendRefs:
        - name: dex
          port: 5556
{{- end }}

    # Root landing: / -> /index.html
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.html
      backendRefs:
        - name: skyforge-server
          port: 8085
    # SPA deep-link rewrite for settings routes.
    - matches:
        - path:
            type: Exact
            value: /settings
        - path:
            type: PathPrefix
            value: /settings/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.html
      backendRefs:
        - name: skyforge-server
          port: 8085

    # Default catch-all to Skyforge server
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: skyforge-server
          port: 8085
{{- if $forwardClusterEnabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: skyforge-forward
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: skyforge
  hostnames:
    - {{ $forwardHost | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $forwardSvcName }}
          namespace: {{ $forwardSvcNamespace }}
          port: {{ int $forwardSvcPort }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: skyforge-tools
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: skyforge
  hostnames:
    - {{ $host | quote }}
  rules:
{{- if .Values.skyforge.s3gw.enabled }}
    # /files/* -> s3gw /<files-bucket>/*
    - matches:
        - path:
            type: PathPrefix
            value: /files/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: {{ printf "/%s/" $filesBucket }}
      backendRefs:
        - name: {{ .Values.skyforge.s3gw.serviceName }}
          port: {{ .Values.skyforge.s3gw.service.port }}
{{- end }}

{{- if $yaadeEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /api-testing
      backendRefs:
        - name: yaade
          port: 80
{{- end }}

{{- if .Values.skyforge.netbox.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /netbox/static/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /static/
      backendRefs:
        - name: netbox
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /netbox/media/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /media/
      backendRefs:
        - name: netbox
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /netbox
      backendRefs:
        - name: netbox-sso-proxy
          port: 8080
{{- end }}

{{- if .Values.skyforge.nautobot.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /nautobot
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Skyforge-External-Prefix
                value: /nautobot
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: nautobot-sso-proxy
          port: 8080
{{- end }}

{{- if $giteaEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /git
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /git
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: gitea-sso-proxy
          port: 8080
{{- end }}

{{- if $redocEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /redoc
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Skyforge-External-Prefix
                value: /redoc
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: redoc-sso-proxy
          port: 8080
{{- end }}

{{- if $coderEnabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /coder
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: coder
          port: 7080
    - matches:
        - path:
            type: PathPrefix
            value: /api/v2
      backendRefs:
        - name: coder
          port: 7080
{{- end }}

{{- if .Values.skyforge.dns.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /dns
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: technitium-dns
          port: 5380
{{- end }}
