{{- $vals := fromYaml (toYaml .Values) -}}
{{- $install := dig "skyforge" "clabernetes" "multus" "install" true $vals -}}
{{- if and .Values.skyforge.clabernetes.enabled $install -}}
{{- $ns := dig "skyforge" "clabernetes" "multus" "namespace" "kube-system" $vals -}}
{{- $image := dig "skyforge" "clabernetes" "multus" "image" "ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick" $vals -}}
{{- $pullPolicy := dig "skyforge" "clabernetes" "multus" "imagePullPolicy" "IfNotPresent" $vals -}}
# Based on the Multus "thick" quickstart manifest:
# https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-thick.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
      - pods/status
    verbs: ["get", "list", "update", "watch"]
  - apiGroups: ["", "events.k8s.io"]
    resources:
      - events
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
  - kind: ServiceAccount
    name: multus
    namespace: {{ $ns | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: {{ $ns | quote }}
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-daemon-config
  namespace: {{ $ns | quote }}
  labels:
    tier: node
    app: multus
    {{- include "skyforge.labels" . | nindent 4 }}
data:
  daemon-config.json: |
    {
        "chrootDir": "/hostroot",
        "cniVersion": "0.3.1",
        "logLevel": "verbose",
        "logToStderr": true,
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusAutoconfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "socketDir": "/host/run/multus/"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-primary-config
  namespace: {{ $ns | quote }}
  labels:
    tier: node
    app: multus
    {{- include "skyforge.labels" . | nindent 4 }}
data:
  00-multus.conf: |
    {
      "cniVersion": "0.3.1",
      "name": "multus-cni-network",
      "type": "multus",
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "cniConfDir": "/etc/cni/multus/net.d",
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "cilium",
          "plugins": [
            {
              "type": "cilium-cni",
              "enable-debug": false,
              "log-file": "/var/run/cilium/cilium-cni.log"
            }
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: {{ $ns | quote }}
  labels:
    tier: node
    app: multus
    name: multus
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
        {{- include "skyforge.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      serviceAccountName: multus
      initContainers:
        - name: install-multus-primary-conf
          image: {{ .Values.images.alpine | quote }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -lc
            - |
              set -euo pipefail
              mkdir -p /host/etc/cni/net.d
              cp -f /config/00-multus.conf /host/etc/cni/net.d/00-multus.conf
              chmod 0600 /host/etc/cni/net.d/00-multus.conf
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cni
              mountPath: /host/etc/cni/net.d
            - name: multus-primary-config
              mountPath: /config
        - name: install-multus-binary
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pullPolicy | quote }}
          command:
            - /usr/src/multus-cni/bin/install_multus
            - -d
            - /host/opt/cni/bin
            - -t
            - thick
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
      containers:
        - name: kube-multus
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pullPolicy | quote }}
          command:
            - /usr/src/multus-cni/bin/multus-daemon
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cni
              mountPath: /host/etc/cni/net.d
            - name: cnibin
              mountPath: /opt/cni/bin
            - name: host-run
              mountPath: /host/run
            - name: host-var-lib-cni-multus
              mountPath: /var/lib/cni/multus
            - name: host-var-lib-kubelet
              mountPath: /var/lib/kubelet
              mountPropagation: HostToContainer
            - name: host-run-k8s-cni-cncf-io
              mountPath: /run/k8s.cni.cncf.io
            - name: host-run-netns
              mountPath: /run/netns
              mountPropagation: HostToContainer
            - name: multus-daemon-config
              mountPath: /etc/cni/net.d/multus.d
              readOnly: true
            - name: hostroot
              mountPath: /hostroot
              mountPropagation: HostToContainer
            - name: multus-conf-dir
              mountPath: /etc/cni/multus/net.d
          env:
            - name: MULTUS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: host-run
          hostPath:
            path: /run
        - name: host-var-lib-cni-multus
          hostPath:
            path: /var/lib/cni/multus
        - name: host-var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: host-run-k8s-cni-cncf-io
          hostPath:
            path: /run/k8s.cni.cncf.io
        - name: host-run-netns
          hostPath:
            path: /run/netns
        - name: multus-daemon-config
          configMap:
            name: multus-daemon-config
        - name: multus-primary-config
          configMap:
            name: multus-primary-config
        - name: hostroot
          hostPath:
            path: /
        - name: multus-conf-dir
          hostPath:
            path: /etc/cni/multus/net.d
{{- end -}}
