{{- if and .Values.skyforge .Values.skyforge.nodeMetrics .Values.skyforge.nodeMetrics.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: skyforge-node-telegraf
  labels:
    app.kubernetes.io/name: skyforge-node-telegraf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: skyforge-node-telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skyforge-node-telegraf
    spec:
      {{- with .Values.kubernetes.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: telegraf
          image: {{ required "images.telegraf is required when skyforge.nodeMetrics.enabled=true" .Values.images.telegraf }}
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/telegraf"]
          args: ["--config", "/etc/telegraf/telegraf.conf"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_PROC
              value: /hostfs/proc
            - name: HOST_SYS
              value: /hostfs/sys
            - name: HOST_ETC
              value: /hostfs/etc
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
              readOnly: true
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_BIND_SERVICE", "SETGID", "SETUID", "SETFCAP"]
              drop: ["ALL"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: telegraf-config
          secret:
            secretName: skyforge-node-telegraf
        - name: hostfs
          hostPath:
            path: /
            type: Directory
{{- end }}
