{{- $pullSecrets := .Values.kubernetes.imagePullSecrets -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skyforge-server
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
{{- if $pullSecrets }}
imagePullSecrets:
{{- range $name := $pullSecrets }}
  - name: {{ $name | quote }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skyforge-server-scaler
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["yaade"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skyforge-server-scaler
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skyforge-server-scaler
subjects:
  - kind: ServiceAccount
    name: skyforge-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skyforge-server-clabernetes
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
rules:
  - apiGroups: ["clabernetes.containerlab.dev"]
    resources: ["topologies"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skyforge-server-clabernetes
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skyforge-server-clabernetes
subjects:
  - kind: ServiceAccount
    name: skyforge-server
    namespace: {{ .Release.Namespace }}
---
