{{- $pullSecrets := .Values.kubernetes.imagePullSecrets -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skyforge-server
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
{{- if $pullSecrets }}
imagePullSecrets:
{{- range $name := $pullSecrets }}
  - name: {{ $name | quote }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skyforge-server-scaler
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["yaade"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skyforge-server-scaler
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skyforge-server-scaler
subjects:
  - kind: ServiceAccount
    name: skyforge-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skyforge-server-cluster
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cilium.io"]
    resources: ["ciliumnodes"]
    verbs: ["get", "list", "watch"]
  # Skyforge manages clabernetes Topology CRs in per-workspace namespaces.
  # Grant these permissions even if the chart doesn't install the clabernetes
  # controller (it may be deployed separately).
  - apiGroups: ["clabernetes.containerlab.dev"]
    resources: ["topologies"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "deletecollection", "watch"]
  - apiGroups: ["clabernetes.containerlab.dev"]
    resources: ["topologies/status", "topologies/finalizers"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "deletecollection", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete", "deletecollection"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete", "deletecollection"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skyforge-server-cluster
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skyforge-server-cluster
subjects:
  - kind: ServiceAccount
    name: skyforge-server
    namespace: {{ .Release.Namespace }}
---
