{{- if .Values.secrets.create }}
{{- range $name, $secret := .Values.secrets.items }}
{{- $type := default "Opaque" (index $secret "_type") }}
{{- $existing := lookup "v1" "Secret" $.Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
{{ include "skyforge.labels" $ | indent 4 }}
type: {{ $type }}
data:
{{- $data := dict -}}
{{- range $key, $value := $secret }}
  {{- if ne $key "_type" }}
    {{- $raw := default "" (tpl (printf "%v" $value) $) }}
    {{- $clean := trimSuffix "\n" $raw }}
    {{- $existingData := "" -}}
    {{- if $existing -}}
      {{- $existingData = default "" (index $existing.data $key) -}}
    {{- end -}}
    {{- $final := "" -}}
    {{- if and (eq $clean "") (ne $existingData "") -}}
      {{- $final = $existingData -}}
    {{- else -}}
      {{- $final = b64enc $clean -}}
    {{- end -}}
    {{- $_ := set $data $key $final -}}
  {{- end -}}
{{- end }}
{{- toYaml $data | nindent 2 }}
---
{{- end }}
{{- end }}
