{{- if .Values.secrets.create }}
{{- range $name, $secret := .Values.secrets.items }}
{{- $type := default "Opaque" (index $secret "_type") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "skyforge.labels" $ | nindent 4 }}
type: {{ $type }}
data:
{{- range $key, $value := $secret }}
  {{- if ne $key "_type" }}
  {{- $raw := default "" (tpl (printf "%v" $value) $) }}
  {{- $clean := trimSuffix "\n" $raw }}
  {{ $key }}: {{ $clean | b64enc }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
