{{- if and (gt (int .Values.skyforge.workerReplicaCount) 0) (.Values.skyforge.workerAutoscaling.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skyforge-server-worker
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skyforge-server-worker
  minReplicas: {{ .Values.skyforge.workerAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.skyforge.workerAutoscaling.maxReplicas }}
  metrics:
    {{- if gt (int .Values.skyforge.workerAutoscaling.targetCPUUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.skyforge.workerAutoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if gt (int .Values.skyforge.workerAutoscaling.targetMemoryUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.skyforge.workerAutoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

