{{- if gt (int .Values.skyforge.workerReplicaCount) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyforge-server-worker
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.skyforge.workerReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: skyforge
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "skyforge.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        checksum/values: {{ sha256sum (toJson .Values) | quote }}
        checksum/infra-worker: {{ sha256sum (.Files.Get "files/infra.config.json") | quote }}
        checksum/encore-cfg-worker: {{ include (print $.Template.BasePath "/encore-cfg-worker-secret.yaml") . | sha256sum | quote }}
        checksum/encore-runtime-worker: {{ include (print $.Template.BasePath "/encore-runtime-config-worker-secret.yaml") . | sha256sum | quote }}
    spec:
      serviceAccountName: skyforge-server
      imagePullSecrets:
        - name: ghcr-pull
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: skyforge
              app.kubernetes.io/component: worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: skyforge
                    app.kubernetes.io/component: worker
      containers:
        - name: skyforge-server-worker
          image: {{ .Values.images.skyforgeServerWorker | default .Values.images.skyforgeServer | quote }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.skyforge.workerResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: skyforge-config
          env:
            - name: SKYFORGE_ROLE
              value: "worker"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENCORE_RUNTIME_CONFIG
              valueFrom:
                secretKeyRef:
                  name: skyforge-encore-runtime-config-worker
                  key: skyforge-encore-runtime-config
                  optional: true
            - name: ENCORE_CFG_WORKER
              valueFrom:
                secretKeyRef:
                  name: skyforge-encore-cfg-worker
                  key: ENCORE_CFG_WORKER
                  optional: true
            - name: SKYFORGE_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: skyforge-session-secret
                  key: skyforge-session-secret
            - name: SKYFORGE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skyforge-admin-shared
                  key: password
            - name: SKYFORGE_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: skyforge-oidc-client-id
                  key: skyforge-oidc-client-id
                  optional: true
            - name: SKYFORGE_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: skyforge-oidc-client-secret
                  key: skyforge-oidc-client-secret
                  optional: true
            - name: SKYFORGE_GEMINI_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.skyforge.gemini.clientSecretSecretName | quote }}
                  key: {{ .Values.skyforge.gemini.clientSecretSecretKey | quote }}
                  optional: true
            - name: SKYFORGE_LDAP_URL
              valueFrom:
                secretKeyRef:
                  name: skyforge-ldap-url
                  key: skyforge-ldap-url
                  optional: true
            - name: SKYFORGE_LDAP_BIND_TEMPLATE
              valueFrom:
                secretKeyRef:
                  name: skyforge-ldap-bind-template
                  key: skyforge-ldap-bind-template
                  optional: true
            - name: SKYFORGE_LDAP_LOOKUP_BINDDN
              valueFrom:
                secretKeyRef:
                  name: skyforge-ldap-lookup-binddn
                  key: skyforge-ldap-lookup-binddn
                  optional: true
            - name: SKYFORGE_LDAP_LOOKUP_BINDPASSWORD
              valueFrom:
                secretKeyRef:
                  name: skyforge-ldap-lookup-bindpassword
                  key: skyforge-ldap-lookup-bindpassword
                  optional: true
            - name: SKYFORGE_GITEA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skyforge-admin-shared
                  key: password
            - name: SKYFORGE_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_REGISTRY_URL
            - name: SKYFORGE_REGISTRY_REPO_PREFIXES
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_REGISTRY_REPO_PREFIXES
            - name: SKYFORGE_REGISTRY_SKIP_TLS_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_REGISTRY_SKIP_TLS_VERIFY
            - name: SKYFORGE_REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.skyforge.registry.usernameSecretName }}
                  key: {{ .Values.skyforge.registry.usernameSecretKey }}
                  optional: true
            - name: SKYFORGE_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.skyforge.registry.passwordSecretName }}
                  key: {{ .Values.skyforge.registry.passwordSecretKey }}
                  optional: true
            - name: SKYFORGE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_DB_HOST
            - name: SKYFORGE_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_DB_PORT
            - name: SKYFORGE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_DB_NAME
            - name: SKYFORGE_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_DB_USER
            - name: SKYFORGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-skyforge-server-password
                  key: db-skyforge-server-password
            - name: SKYFORGE_DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: skyforge-config
                  key: SKYFORGE_DB_SSLMODE
            - name: SKYFORGE_OBJECT_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.skyforge.objectStorage.accessKeySecretName | quote }}
                  key: {{ .Values.skyforge.objectStorage.accessKeySecretKey | quote }}
            - name: SKYFORGE_OBJECT_STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.skyforge.objectStorage.secretKeySecretName | quote }}
                  key: {{ .Values.skyforge.objectStorage.secretKeySecretKey | quote }}
            - name: SKYFORGE_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: skyforge-internal-token
                  key: skyforge-internal-token
                  optional: true
            - name: SKYFORGE_CONTAINERLAB_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: skyforge-containerlab-jwt-secret
                  key: skyforge-containerlab-jwt-secret
                  optional: true
            - name: SKYFORGE_PKI_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: skyforge-pki-ca-cert
                  key: skyforge-pki-ca-cert
                  optional: true
            - name: SKYFORGE_PKI_CA_KEY
              valueFrom:
                secretKeyRef:
                  name: skyforge-pki-ca-key
                  key: skyforge-pki-ca-key
                  optional: true
            - name: SKYFORGE_SSH_CA_KEY
              valueFrom:
                secretKeyRef:
                  name: skyforge-ssh-ca-key
                  key: skyforge-ssh-ca-key
                  optional: true
            - name: SKYFORGE_NETLAB_SERVERS_FILE
              value: /run/secrets/skyforge-netlab-servers
            - name: SKYFORGE_NETLAB_SSH_KEY_FILE
              value: /run/secrets/netlab-runner-rsa
            - name: PORT
              value: "8085"
            - name: SSL_CERT_FILE
              value: /etc/skyforge/ca/ca-certificates.crt
          volumeMounts:
            - mountPath: /encore/infra.config.json
              name: skyforge-server-infra-config-worker
              readOnly: true
              subPath: infra.config.json
            - mountPath: /run/secrets
              name: run-secrets
              readOnly: true
            - mountPath: /var/lib/skyforge
              name: skyforge-worker-data
            - mountPath: /data
              name: skyforge-worker-platform
            - name: skyforge-ca-bundle
              mountPath: /etc/skyforge/ca
      volumes:
        - name: skyforge-server-infra-config-worker
          configMap:
            name: skyforge-server-infra-config-worker
        - name: run-secrets
          projected:
            sources:
              - secret:
                  name: skyforge-netlab-servers
                  optional: true
                  items:
                    - key: skyforge-netlab-servers
                      path: skyforge-netlab-servers
              - secret:
                  name: netlab-runner-rsa
                  optional: true
                  items:
                    - key: netlab-runner-rsa
                      path: netlab-runner-rsa
        - name: skyforge-worker-data
          emptyDir: {}
        - name: skyforge-worker-platform
          emptyDir: {}
        - name: skyforge-ca-cert
          secret:
            secretName: skyforge-ca-cert
        - name: skyforge-ca-bundle
          emptyDir: {}
      initContainers:
        - name: skyforge-ca-bundle
          image: {{ .Values.images.alpine | quote }}
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - cat /etc/ssl/certs/ca-certificates.crt /etc/skyforge/skyforge-ca-cert > /work/ca-certificates.crt
          volumeMounts:
            - name: skyforge-ca-cert
              mountPath: /etc/skyforge
              readOnly: true
            - name: skyforge-ca-bundle
              mountPath: /work
{{- end }}
