apiVersion: v1
kind: Service
metadata:
  name: skyforge-server-worker
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: skyforge
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: 8085
      targetPort: 8085
