apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-reconcile-queued-tasks
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: skyforge-server
          containers:
            - name: reconcile
              image: {{ .Values.images.alpine | quote }}
              imagePullPolicy: IfNotPresent
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
              command:
                - sh
                - -c
                - >
                  apk add --no-cache curl >/dev/null 2>&1 &&
                  curl -fsS -X POST
                  -H "X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  http://skyforge-server:8085/api/internal/tasks/reconcile
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-reconcile-running-tasks
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: skyforge-server
          containers:
            - name: reconcile
              image: {{ .Values.images.alpine | quote }}
              imagePullPolicy: IfNotPresent
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
              command:
                - sh
                - -c
                - >
                  apk add --no-cache curl >/dev/null 2>&1 &&
                  curl -fsS -X POST
                  -H "X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  http://skyforge-server:8085/api/internal/tasks/reconcile-running

