{{- if (default true .Values.skyforge.internalCronjobsEnabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-internal-tasks-reconcile
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: {{ .Values.images.alpine | quote }}
              command:
                - /bin/sh
                - -lc
                - >
                  wget -qO-
                  --header="X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  --post-data=""
                  http://skyforge-server:8085/api/internal/tasks/reconcile >/dev/null
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-internal-tasks-reconcile-running
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: {{ .Values.images.alpine | quote }}
              command:
                - /bin/sh
                - -lc
                - >
                  wget -qO-
                  --header="X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  --post-data=""
                  http://skyforge-server:8085/api/internal/tasks/reconcile-running >/dev/null
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-internal-tasks-metrics
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: {{ .Values.images.alpine | quote }}
              command:
                - /bin/sh
                - -lc
                - >
                  wget -qO-
                  --header="X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  --post-data=""
                  http://skyforge-server:8085/api/internal/tasks/metrics >/dev/null
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-internal-workspaces-sync
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.skyforge.workspaceSyncCron | default "*/5 * * * *" | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: {{ .Values.images.alpine | quote }}
              command:
                - /bin/sh
                - -lc
                - >
                  wget -qO-
                  --header="X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  --post-data=""
                  http://skyforge-server:8085/api/internal/workspaces/sync >/dev/null
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyforge-internal-cloud-checks
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.skyforge.cloudCheckCron | default "*/30 * * * *" | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: {{ .Values.images.alpine | quote }}
              command:
                - /bin/sh
                - -lc
                - >
                  wget -qO-
                  --header="X-Skyforge-Internal-Token: ${SKYFORGE_INTERNAL_TOKEN}"
                  --post-data=""
                  http://skyforge-server:8085/api/internal/cloud/checks >/dev/null
              env:
                - name: SKYFORGE_INTERNAL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: skyforge-internal-token
                      key: skyforge-internal-token
{{- end }}
