{{- /*
SSO reverse proxies for tool UIs behind Cilium Gateway API.

Goal:
- No Traefik.
- No NGINX.
- Still enforce Skyforge SSO and inject identity headers for tools that don't natively speak OIDC.

Approach:
- Run small Envoy proxies per tool that:
  1) call Skyforge auth endpoint via `envoy.filters.http.ext_authz`
  2) inject returned identity headers into the upstream request
  3) redirect unauthenticated users to `/api/oidc/login?next=...`

We keep these proxies per-tool so redirects preserve each tool's external prefix
(/git, /nautobot, etc.) even when the Gateway URL-rewrites the prefix away.
*/ -}}

{{- define "skyforge.ssoProxyEnvoy" -}}
{{- $root := .root -}}
{{- $name := .name -}}
{{- $upstreamHost := .upstreamHost -}}
{{- $upstreamPort := .upstreamPort -}}
{{- $externalPrefix := .externalPrefix -}}
{{- $ns := $root.Release.Namespace -}}
{{- $envoyImage := default "envoyproxy/envoy:v1.31.2" $root.Values.images.envoy -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-envoy
  labels:
    {{- include "skyforge.labels" $root | nindent 4 }}
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

    static_resources:
      listeners:
        - name: listener_http
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    normalize_path: true
                    use_remote_address: true
                    stream_idle_timeout: 300s
                    upgrade_configs:
                      - upgrade_type: websocket
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: /
                              route:
                                cluster: upstream
                    http_filters:
                      - name: envoy.filters.http.ext_authz
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                          transport_api_version: V3
                          failure_mode_allow: false
                          http_service:
                            server_uri:
                              uri: http://skyforge-server.{{ $ns }}.svc.cluster.local:8085
                              cluster: skyforge_server
                              timeout: 2s
                            path_prefix: /api/session/forwardauth/envoy
                            authorization_request:
                              allowed_headers:
                                patterns:
                                  - exact: cookie
                                  - exact: x-forwarded-proto
                                  - exact: x-forwarded-host
                                  - exact: x-forwarded-for
                                  - exact: x-forwarded-uri
                                  - exact: x-forwarded-prefix
                                  - exact: user-agent
                                  - exact: accept
                                  - exact: accept-language
                                  - exact: x-skyforge-external-prefix
                            authorization_response:
                              allowed_upstream_headers:
                                patterns:
                                  - exact: remote-user
                                  - exact: remote-user-group
                                  - exact: remote-user-email
                                  - exact: remote-user-first-name
                                  - exact: remote-user-last-name
                                  - exact: x-forwarded-user
                                  - exact: x-forwarded-email
                                  - exact: x-forwarded-first-name
                                  - exact: x-forwarded-last-name
                              allowed_client_headers:
                                patterns:
                                  - exact: location
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: skyforge_server
          type: STRICT_DNS
          connect_timeout: 2s
          load_assignment:
            cluster_name: skyforge_server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: skyforge-server.{{ $ns }}.svc.cluster.local
                          port_value: 8085

        - name: upstream
          type: STRICT_DNS
          connect_timeout: 5s
          load_assignment:
            cluster_name: upstream
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ $upstreamHost }}.{{ $ns }}.svc.cluster.local
                          port_value: {{ $upstreamPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "skyforge.labels" $root | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        app.kubernetes.io/component: sso-proxy
    spec:
      automountServiceAccountToken: false
      containers:
        - name: envoy
          image: {{ $envoyImage | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "/etc/envoy/envoy.yaml"
          ports:
            - name: http
              containerPort: 8080
            - name: admin
              containerPort: 9901
          readinessProbe:
            httpGet:
              path: /ready
              port: 9901
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ready
              port: 9901
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: envoy-conf
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-conf
          configMap:
            name: {{ $name }}-envoy
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "skyforge.labels" $root | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
{{- end -}}

{{- if .Values.skyforge.netbox.enabled }}
{{ include "skyforge.ssoProxyEnvoy" (dict "root" $ "name" "netbox-sso-proxy" "upstreamHost" "netbox" "upstreamPort" 8080 "externalPrefix" "") }}
{{- end }}

{{- if .Values.skyforge.nautobot.enabled }}
{{ include "skyforge.ssoProxyEnvoy" (dict "root" $ "name" "nautobot-sso-proxy" "upstreamHost" "nautobot" "upstreamPort" 8080 "externalPrefix" "/nautobot") }}
{{- end }}

{{- if .Values.skyforge.gitea.enabled }}
{{ include "skyforge.ssoProxyEnvoy" (dict "root" $ "name" "gitea-sso-proxy" "upstreamHost" "gitea" "upstreamPort" 3000 "externalPrefix" "/git") }}
{{- end }}

{{- $elastic := (get .Values.skyforge "elastic" | default (dict)) -}}
{{- if (get $elastic "enabled" | default false) }}
{{ include "skyforge.ssoProxyEnvoy" (dict "root" $ "name" "kibana-sso-proxy" "upstreamHost" "kibana" "upstreamPort" 5601 "externalPrefix" (default "/kibana" (get $elastic "kibanaSubpath"))) }}
{{- end }}
