{{- $vals := fromYaml (toYaml .Values) -}}
{{- $install := dig "skyforge" "clabernetes" "whereabouts" "install" false $vals -}}
{{- if and .Values.skyforge.clabernetes.enabled $install -}}
{{- $ns := dig "skyforge" "clabernetes" "whereabouts" "namespace" "kube-system" $vals -}}
{{- $image := dig "skyforge" "clabernetes" "whereabouts" "image" "ghcr.io/k8snetworkplumbingwg/whereabouts:v0.8.0" $vals -}}
{{- $pullPolicy := dig "skyforge" "clabernetes" "whereabouts" "imagePullPolicy" "IfNotPresent" $vals -}}
{{- $cron := dig "skyforge" "clabernetes" "whereabouts" "cronExpression" "30 4 * * *" $vals -}}
{{- $nodeSliceEnabled := dig "skyforge" "clabernetes" "whereabouts" "nodeSliceController" "enabled" true $vals -}}
# Based on the upstream Whereabouts Helm chart (k8snetworkplumbingwg/whereabouts).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whereabouts
  namespace: {{ $ns | quote }}
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whereabouts
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - whereabouts.cni.cncf.io
    resources:
      - ippools
      - overlappingrangeipreservations
      - nodeslicepools
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - network-attachment-definitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: whereabouts
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whereabouts
subjects:
  - kind: ServiceAccount
    name: whereabouts
    namespace: {{ $ns | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: {{ $ns | quote }}
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
data:
  cron-expression: {{ $cron | quote }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whereabouts
  namespace: {{ $ns | quote }}
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: whereabouts
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whereabouts
        {{- include "skyforge.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: whereabouts
      securityContext: {}
      containers:
        - name: whereabouts
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:
            - -c
            - |
              SLEEP=false source /install-cni.sh
              /token-watcher.sh &
              /ip-control-loop -log-level debug
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: WHEREABOUTS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
            - name: cni-net-dir
              mountPath: /host/etc/cni/net.d
            - name: cron-scheduler-configmap
              mountPath: /cron-schedule
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: cron-scheduler-configmap
          configMap:
            name: whereabouts-config
            defaultMode: 0744
            items:
              - key: "cron-expression"
                path: "config"
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
          effect: NoSchedule
---
{{- if $nodeSliceEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereabouts-node-slice-controller
  namespace: {{ $ns | quote }}
  labels:
    {{- include "skyforge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereabouts-node-slice-controller
  template:
    metadata:
      labels:
        app: whereabouts-node-slice-controller
        {{- include "skyforge.labels" . | nindent 8 }}
    spec:
      serviceAccountName: whereabouts
      containers:
        - name: whereabouts-node-slice-controller
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          command: ["/node-slice-controller"]
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: WHEREABOUTS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
            - name: cni-net-dir
              mountPath: /host/etc/cni/net.d
            - name: cron-scheduler-configmap
              mountPath: /cron-schedule
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: cron-scheduler-configmap
          configMap:
            name: whereabouts-config
            defaultMode: 0744
            items:
              - key: "cron-expression"
                path: "config"
{{- end }}
{{- end }}

